# <center> 1. Librerias

In [1]:
import sys
from pathlib import Path

# 1. Encontrar la raíz del proyecto (subir un nivel desde la carpeta 'notebooks')
# Si tu notebook está en la raíz, usá Path(".").resolve()
ROOT_DIR = Path("..").resolve()

# 2. Agregar la raíz al sistema de Python si no está cargada
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))
import os    
import pandas as pd
import numpy as np
import openpyxl
from src.preprocessing.ipc import format_df_IPC
from src.preprocessing.common import format_df, save_csv
from src.paths import (
    AUH_DIR,
    CBTA_DIR,
    IPC_DIR,
    EPH_DIR,
    ENGHO_DIR,
    INTERIM_DIR,
)
%load_ext autoreload
%autoreload 2

# <center> 2. Carga y Ajuste de Estructura

## <center> Cargamos AUH

In [2]:
hojas_auh = pd.read_excel(AUH_DIR/"AUH_data.xlsx", sheet_name=None)
hojas_auh

{'Boletín ': Empty DataFrame
 Columns: []
 Index: [],
 'Contenido ':                                            Unnamed: 0  \
 0   Boletín mensual de Asignaciones para Protecció...
 1                                     Febrero de 2026
 2                                                 NaN
 3                                                 NaN
 4                                           Contenido
 5                                                 NaN
 6                                    1. Beneficiarios
 7                                                 1.1
 8                                               1.1.A
 9                                               1.1.B
 10                                                1.2
 11                                              1.2.A
 12                                              1.2.B
 13                                                1.3
 14                                                1.4
 15                                                1.5
 16                                                1.6
 17                                                1.7
 18                                                1.8
 19                                                1.9
 20                                                NaN
 21                                       2. Titulares
 22                                                2.1
 23                                                2.2
 24                                                2.3
 25                                                2.4
 26                                                NaN
 27                                          3. Montos
 28                                                3.1
 29                                                3.2
 30                                                3.3
 31                                                3.4
 32                                                3.5
 33                                                3.6
 34                                                NaN
 35                            4. Corresponsabilidades
 36                                                4.1
 37                                                NaN
 38        5. Menores de 18 años en registros de ANSES
 39                                                5.1
 40                                                NaN
 41                      6. Eficiencia de la cobertura
 42                                                6.1
 43                                                6.2
 44                                                6.3

                                            Unnamed: 1
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                                                 NaN
 4                                                 NaN
 5                                                 NaN
 6                                                 NaN
 7   Beneficiarios de la Asignación Universal por H...
 8   Beneficiarios de la Asignación Universal por H...
 9   Beneficiarios de la Asignación Universal por H...
 10  Beneficiarios de la Asignación Universal por H...
 11  Beneficiarios de la Asignación Universal por H...
 12  Beneficiarios de la Asignación Universal por H...
 13  Beneficiarios de la Asignación Universal por H...
 14  Beneficiarios de la Asignación Universal por H...
 15  Beneficiarios de la Asignación por Hijo del Si...
 16  Población total menor de 18 años en el Adminis...
 17  Menores de 18 años en el Administrador de Dato...
 18  Beneficiarios de la Asignación por Embarazo, p...
 19  Beneficiarios del Apoyo Alimentario - Ley 1000...
 20                                                NaN
 21                                                NaN
 22  Titulares de la Asignación Universal por Hijo ...
 23  Titulares de la Asignación Universal por Hijo ...
 24  Titulares de la Asignación Universal por Hijo ...
 25  Titulares del Apoyo Alimentario - Ley 1000 Día...
 26                                                NaN
 27                                                NaN
 28  Montos liquidados, en miles de pesos, de la As...
 29  Montos liquidados, en miles de pesos, de la As...
 30  Montos liquidados, en miles de pesos, de la As...
 31  Montos liquidados, en miles de pesos, del Apoy...
 32  Valor general, en pesos corrientes, de la Asig...
 33  Valor general de la Asignación Universal por H...
 34                                                NaN
 35                                                NaN
 36  Beneficiarios con corresponsabilidades cumplidas.
 37                                                NaN
 38                                                NaN
 39  Cantidad de menores de 18 años con registros c...
 40                                                NaN
 41                                                NaN
 42  Tiempo promedio, en semanas, que las beneficia...
 43  Proporción de beneficiarias de la Asignación p...
 44  Proporción de beneficiarios de la Asignación U...  ,
 'Consideraciones - Definiciones':                                            Unnamed: 0
 0   Boletín mensual de Asignaciones para Protecció...
 1                                                 NaN
 2                                        Definiciones
 3                                                 NaN
 4                       ASIGNACIÓN UNIVERSAL POR HIJO
 5                                                 NaN
 6   Beneficiarios: se consideran los niños, adoles...
 7                                                 NaN
 8   Montos liquidados: se consideran los montos de...
 9                                                 NaN
 10  Titulares:  persona que recibe la asignación e...
 11                                                NaN
 12  Valor general de la prestación: monto del 100%...
 13                                                NaN
 14     Periodo: corresponde al mes de la liquidación.
 15                                                NaN
 16  Corresponsabilidades: la asignación incluye co...
 17                                                NaN
 18                                                NaN
 19                            ASIGNACIÓN POR EMBARAZO
 20                                                NaN
 21  Beneficiaria: corresponde a la embarazada a la...
 22                                                NaN
 23  Montos liquidados: se consideran los montos de...
 24                                                NaN
 25  Valor general de la prestación: monto del 100%...
 26                                                NaN
 27     Periodo: corresponde al mes de la liquidación.
 28                                                NaN
 29  Tiempo promedio de cobertura: corresponde a la...
 30                                                NaN
 31                                                NaN
 32                  APOYO ALIMENTARIO - LEY 1000 DÍAS
 33                                                NaN
 34  Beneficiarios: niños y niñas beneficiarios de ...
 35                                                NaN
 36  Titulares: persona que recibe la asignación en...
 37                                                NaN
 38     Periodo: corresponde al mes de la liquidación.
 39                                                NaN
 40                                                NaN
 41                                                NaN
 42                                                NaN
 43                                                NaN
 44                          Consideraciones generales
 45                                                NaN
 46  A partir de junio de 2019 ANSES implementó el ...
 47  Hasta ese momento la liquidación de las asigna...
 48  Por este motivo, en esta publicación se presen...
 49  Entre las mejoras introducidas por CUNA, se de...
 50  Asimismo, en los sistemas anteriores se regist...
 51  La información de asignaciones familiares (con...,
 '1.1 Benef. H Edad':    Cuadro 1.1 - Beneficiarios de la Asignación Universal por Hijo, por mes, según edad simple  \
 0                                                 NaN
 1                                             Periodo
 2                                                 NaN
 3                                 2016-12-01 00:00:00
 4                                 2017-12-01 00:00:00
 5                                 2018-12-01 00:00:00
 6                                 2019-12-01 00:00:00
 7                                 2020-12-01 00:00:00
 8                                 2021-12-01 00:00:00
 9                                 2022-12-01 00:00:00
 10                                2023-12-01 00:00:00
 11                                2024-01-01 00:00:00
 12                                2024-02-01 00:00:00
 13                                2024-03-01 00:00:00
 14                                2024-04-01 00:00:00
 15                                2024-05-01 00:00:00
 16                                2024-06-01 00:00:00
 17                                2024-07-01 00:00:00
 18                                2024-08-01 00:00:00
 19                                2024-09-01 00:00:00
 20                                2024-10-01 00:00:00
 21                                2024-11-01 00:00:00
 22                                2024-12-01 00:00:00
 23                                2025-01-01 00:00:00
 24                                2025-02-01 00:00:00
 25                                2025-03-01 00:00:00
 26                                2025-04-01 00:00:00
 27                                2025-05-01 00:00:00
 28                                2025-06-01 00:00:00
 29                                2025-07-01 00:00:00
 30                                2025-08-01 00:00:00
 31                                2025-09-01 00:00:00
 32                                2025-10-01 00:00:00
 33                                2025-11-01 00:00:00
 34                                2025-12-01 00:00:00
 35                                2026-01-01 00:00:00
 36                                2026-02-01 00:00:00
 37                                                NaN
 38  Nota: el periodo corresponde al mes de liquida...
 39                                                NaN
 40                                      Fuente: ANSES

    Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
 0         NaN         NaN         NaN         NaN         NaN         NaN
 1        Edad         NaN         NaN         NaN         NaN         NaN
 2           0         1.0         2.0         3.0         4.0         5.0
 3      221204    294273.0    305516.0    278808.0    264017.0    255396.0
 4      217017    276495.0    292007.0    289250.0    266548.0    255442.0
 5      225566    273623.0    277648.0    281744.0    283139.0    261683.0
 6      237967    287037.0    285372.0    280509.0    288034.0    290182.0
 7      192690    261463.0    289787.0    285011.0    281345.0    289408.0
 8      192369    235801.0    256840.0    281433.0    277775.0    276024.0
 9      189784    214603.0    230316.0    247090.0    270294.0    267716.0
 10     170614    194589.0    201630.0    215240.0    229001.0    249949.0
 11     167248    194353.0    202028.0    212310.0    228104.0    248628.0
 12     167259    195512.0    203026.0    211692.0    228451.0    249185.0
 13     164184    196034.0    203960.0    211963.0    227544.0    249437.0
 14     165407    195752.0    205057.0    211478.0    227153.0    250232.0
 15     166179    194839.0    205620.0    209745.0    224752.0    248442.0
 16     163627    194582.0    206372.0    208997.0    224677.0    246831.0
 17     166613    194435.0    206939.0    208299.0    224004.0    245397.0
 18     168276    193405.0    206853.0    207283.0    222419.0    242142.0
 19     169265    193376.0    205891.0    206272.0    222239.0    240539.0
 20     168948    193654.0    203401.0    205202.0    221149.0    237820.0
 21     167761    194487.0    203367.0    206133.0    222445.0    236659.0
 22     165038    190801.0    200433.0    205727.0    218474.0    232339.0
 23     161957    188863.0    200028.0    206070.0    215164.0    231085.0
 24     161095    187021.0    200056.0    205782.0    213815.0    229496.0
 25     158425    184951.0    200014.0    206018.0    213080.0    228056.0
 26     158378    184734.0    198801.0    206339.0    211912.0    226595.0
 27     157374    183819.0    197683.0    206949.0    210104.0    224596.0
 28     158076    182652.0    196628.0    207350.0    208674.0    224194.0
 29     157641    182557.0    195534.0    206905.0    207299.0    222456.0
 30     158842    182230.0    194801.0    206932.0    206403.0    221469.0
 31     159469    181554.0    194197.0    205359.0    204992.0    220668.0
 32     160193    180178.0    194294.0    203170.0    204120.0    219672.0
 33     161233    178055.0    194094.0    201810.0    203922.0    219904.0
 34     162452    176626.0    192500.0    201107.0    205496.0    218111.0
 35     161990    175107.0    190619.0    200622.0    205811.0    215365.0
 36     161534    174711.0    188726.0    200951.0    205733.0    213957.0
 37        NaN         NaN         NaN         NaN         NaN         NaN
 38        NaN         NaN         NaN         NaN         NaN         NaN
 39        NaN         NaN         NaN         NaN         NaN         NaN
 40        NaN         NaN         NaN         NaN         NaN         NaN

     Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 11  Unnamed: 12  \
 0          NaN         NaN         NaN  ...          NaN          NaN
 1          NaN         NaN         NaN  ...          NaN          NaN
 2          6.0         7.0         8.0  ...         10.0         11.0
 3     246457.0    234558.0    224343.0  ...     197797.0     192204.0
 4     246211.0    238545.0    227109.0  ...     199499.0     191602.0
 5     250776.0    242426.0    234388.0  ...     213603.0     195798.0
 6     268396.0    256782.0    248526.0  ...     228939.0     219186.0
 7     291620.0    268319.0    257360.0  ...     241243.0     229990.0
 8     285093.0    288214.0    266003.0  ...     247322.0     239406.0
 9     267126.0    276236.0    280350.0  ...     249188.0     241571.0
 10    247083.0    247477.0    256639.0  ...     242232.0     232662.0
 11    247592.0    246955.0    254332.0  ...     243213.0     233565.0
 12    248703.0    248040.0    255649.0  ...     245981.0     235168.0
 13    248740.0    249857.0    255264.0  ...     248272.0     236693.0
 14    249797.0    251077.0    255309.0  ...     250540.0     239562.0
 15    248702.0    250552.0    253239.0  ...     251729.0     238929.0
 16    250006.0    250991.0    253289.0  ...     254854.0     239387.0
 17    252183.0    250881.0    253868.0  ...     258275.0     240384.0
 18    252885.0    250456.0    254094.0  ...     260072.0     240602.0
 19    253532.0    250353.0    253590.0  ...     262139.0     241677.0
 20    253605.0    250474.0    251779.0  ...     262304.0     242413.0
 21    255072.0    252669.0    252894.0  ...     265107.0     245558.0
 22    252833.0    249818.0    250540.0  ...     264479.0     245859.0
 23    251235.0    250150.0    249766.0  ...     265292.0     246757.0
 24    250425.0    250166.0    249624.0  ...     266160.0     247960.0
 25    249989.0    249326.0    249930.0  ...     268120.0     249392.0
 26    249895.0    249305.0    249990.0  ...     268801.0     250879.0
 27    248690.0    249309.0    250879.0  ...     268140.0     253003.0
 28    246552.0    249813.0    250910.0  ...     268003.0     255787.0
 29    244119.0    250956.0    250027.0  ...     266849.0     258337.0
 30    241467.0    252342.0    250261.0  ...     266226.0     260507.0
 31    239419.0    252565.0    249560.0  ...     265299.0     262489.0
 32    236698.0    252707.0    249893.0  ...     264296.0     262518.0
 33    233880.0    252907.0    250771.0  ...     263184.0     263769.0
 34    232155.0    253556.0    250569.0  ...     260880.0     265707.0
 35    231035.0    251964.0    250866.0  ...     258179.0     266867.0
 36    229883.0    251251.0    250660.0  ...     257346.0     267758.0
 37         NaN         NaN         NaN  ...          NaN          NaN
 38         NaN         NaN         NaN  ...          NaN          NaN
 39         NaN         NaN         NaN  ...          NaN          NaN
 40         NaN         NaN         NaN  ...          NaN          NaN

     Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  \
 0           NaN          NaN          NaN          NaN          NaN
 1           NaN          NaN          NaN          NaN          NaN
 2          12.0         13.0         14.0         15.0         16.0
 3      192068.0     179677.0     175663.0     161144.0     158062.0
 4      186150.0     185489.0     172930.0     167499.0     151772.0
 5      187428.0     181441.0     179791.0     166051.0     158943.0
 6      200759.0     192278.0     185809.0     182662.0     167423.0
 7      220873.0     202362.0     193858.0     187341.0     184514.0
 8      228545.0     218844.0     200699.0     191237.0     184456.0
 9      234139.0     223598.0     213416.0     195247.0     185040.0
 10     225897.0     218392.0     207675.0     197426.0     180011.0
 11     225818.0     218752.0     207342.0     198414.0     180185.0
 12     227668.0     221333.0     208514.0     199704.0     182086.0
 13     228907.0     223609.0     210066.0     202234.0     183491.0
 14     230066.0     225217.0     212555.0     203021.0     186618.0
 15     230032.0     224772.0     213072.0     202943.0     187169.0
 16     231329.0     225370.0     214510.0     204859.0     188980.0
 17     233059.0     226352.0     216449.0     206779.0     190950.0
 18     233776.0     227319.0     217503.0     207324.0     192027.0
 19     234712.0     228210.0     218868.0     207567.0     194466.0
 20     236205.0     228692.0     218307.0     208420.0     195686.0
 21     237704.0     231115.0     219995.0     210373.0     198126.0
 22     236487.0     229478.0     219557.0     208932.0     197933.0
 23     237329.0     229065.0     220810.0     209009.0     199272.0
 24     238131.0     228927.0     222565.0     209582.0     200524.0
 25     238542.0     229946.0     224372.0     210916.0     202228.0
 26     240372.0     230464.0     225282.0     212643.0     202645.0
 27     240449.0     231180.0     225642.0     213894.0     203526.0
 28     240391.0     232084.0     226033.0     215062.0     205136.0
 29     240571.0     233022.0     226104.0     216193.0     206433.0
 30     241163.0     234284.0     227532.0     217764.0     207628.0
 31     241807.0     234735.0     228045.0     219021.0     207443.0
 32     242398.0     235988.0     228304.0     218371.0     208018.0
 33     244555.0     236687.0     229433.0     218980.0     209042.0
 34     247086.0     237909.0     229883.0     220793.0     209764.0
 35     247995.0     238819.0     229816.0     222119.0     209935.0
 36     249375.0     239624.0     229857.0     224009.0     210685.0
 37          NaN          NaN          NaN          NaN          NaN
 38          NaN          NaN          NaN          NaN          NaN
 39          NaN          NaN          NaN          NaN          NaN
 40          NaN          NaN          NaN          NaN          NaN

     Unnamed: 18  Unnamed: 19 Volver al índice
 0           NaN          NaN              NaN
 1           NaN        Total              NaN
 2          17.0          NaN              NaN
 3      154590.0      3941618              NaN
 4      156576.0      3937689              NaN
 5      151759.0      3989385              NaN
 6      170648.0      4231199              NaN
 7      183507.0      4309864              NaN
 8      195275.0      4320566              NaN

In [3]:
nombres_hojas = list(hojas_auh.keys())
print(f"Hojas encontradas en el archivo de AUH: {nombres_hojas}\n")

Hojas encontradas en el archivo de AUH: ['Boletín ', 'Contenido ', 'Consideraciones - Definiciones', '1.1 Benef. H Edad', '1.1.A Benef. H Muj Edad ', '1.1.B Benef. H Var Edad', '1.2 Benef. HD Edad', '1.2.A Benef. HD Muj Edad', '1.2.B Benef. HD Var Edad', '1.3 Benef. Ciclo Lect', '1.4 Benef. Situ. Mayor', '1.5 SUAF x sexo', '1.6 Población ', '1.7 Apertura otras incompatib', '1.8 Benef AxE', '1.9 Benef Apoyo Alimentario', '2.1 Titu. Sexo', '2.2 Titu Edad', '2.3 Hijos por Titu', '2.4 Titu Apoyo Alimentario', '3.1 Importes Liq.', '3.2 Importes Liq. SUAF', '3.3 Importes Liq AxE', '3.4 Importes Liq. Apoyo Alim', '3.5 Valor general pago', '3.6 Valor general-$ Feb 26', '4.1 Corresponsabilidades', '5.1 Indicador', '6.1 Tiempo Prom Cob', '6.2 Benef AxE forma acceso', '6.3 Corresponsabilidad automáti']

## Vemos que tenemos multiples hojas, nos quedamos solo con las que nos hagan falta.

### Valores generales de la AUH:

In [4]:
hojas_auh['3.5 Valor general pago'].head()

,"Cuadro 3.5 - Valor general, en pesos corrientes, de la Asignación Universal por Hijo e Hijo con Discapacidad, de la Asignación por embarazo y del Apoyo Alimentario - Ley 1000 días",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Volver al índice
0,NaN,NaN,NaN,NaN,NaN,NaN
1,Periodo,Hijo,Hijo con Discapacidad,Asignación por Embarazo,Apoyo Alimentario - Ley 1000 días,NaN
2,2009-10-01 00:00:00,180,720,NaN,NaN,NaN
3,2010-10-01 00:00:00,220,880,NaN,NaN,NaN
4,2011-05-01 00:00:00,220,880,220,NaN,NaN

### Arreglemos la estructura:

In [5]:
df_AUH_valor_general = format_df('3.5 Valor general pago', hojas_auh, 2, -4, 1)

In [6]:
df_AUH_valor_general.head()

1,Periodo,Hijo,Hijo con Discapacidad,Asignación por Embarazo,Apoyo Alimentario - Ley 1000 días
0,2009-10-01 00:00:00,180,720,NaN,NaN
1,2010-10-01 00:00:00,220,880,NaN,NaN
2,2011-05-01 00:00:00,220,880,220,NaN
3,2011-09-01 00:00:00,270,1080,270,NaN
4,2012-09-01 00:00:00,340,1200,340,NaN

### Edades de los titulares del beneficio:

In [7]:
hojas_auh['2.2 Titu Edad'].tail()

,"Cuadro 2.2 - Titulares de la Asignación Universal por Hijo por mes, según grupo de edad",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Volver al índice
36,2026-02-01 00:00:00,47631,250707,469085,536368,436850,309353,200084,88102,28329,4757,536,236,4721,2376759,34.257115,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Nota: el periodo corresponde al mes de liquida...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Fuente: ANSES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Arreglemos la estructura:

In [8]:
# 1. Seleccionamos las filas 1 y 2 (la fila 0 está vacía, no aporta datos)
encabezados = hojas_auh['2.2 Titu Edad'].iloc[1:3]

# 2. Fusionamos la fila 2 (rangos de edad) rellenando sus NaN con la fila 1 (Periodo, Total, etc.)
nuevas_columnas = encabezados.iloc[1].fillna(encabezados.iloc[0])

# 3. Asignamos los nombres resultantes como las columnas oficiales del DataFrame
hojas_auh['2.2 Titu Edad'].columns = nuevas_columnas

# 4. Eliminamos las filas de encabezado (0, 1 y 2) para dejar solo los datos numéricos abajo
df_AUH_edad_titular = hojas_auh['2.2 Titu Edad'].iloc[3:-4].reset_index(drop=True)
df_AUH_edad_titular = df_AUH_edad_titular.loc[:, df_AUH_edad_titular.columns.notna()]

In [9]:
df_AUH_edad_titular.tail()

2,Periodo,15 - 19,20 - 24,25 - 29,30 - 34,35 - 39,40 - 44,45 - 49,50 - 54,55 - 59,60 - 64,65 - 69,Más de 70,Sin datos,Total,Edad Promedio
29,2025-10-01 00:00:00,49257,256974,474493,530194,428984,305007,195810,86289,27387,4434,510,232,4400,2363971,34.128514
30,2025-11-01 00:00:00,48826,255570,473359,531912,431046,305653,197222,86771,27654,4529,494,233,4489,2367758,34.160209
31,2025-12-01 00:00:00,48429,254085,472109,534062,433524,307079,198770,87309,27994,4573,520,231,4587,2373272,34.196781
32,2026-01-01 00:00:00,47981,252126,470424,534868,434918,308168,199169,87617,28102,4622,518,233,4570,2373316,34.225823
33,2026-02-01 00:00:00,47631,250707,469085,536368,436850,309353,200084,88102,28329,4757,536,236,4721,2376759,34.257115

##  <center>Cargamos CBT Y CBA

In [10]:
CBA = pd.read_csv(CBTA_DIR/"canasta-basica-alimentaria-regiones-del-pais.csv")
CBT = pd.read_csv(CBTA_DIR/"canasta-basica-total-regiones-del-pais.csv")
pobreza_indigencia = pd.read_csv(CBTA_DIR/"valores-canasta-basica-alimentos-canasta-basica-total-mensual-2016.csv")

### Veamos los datos de la canasta basica alimentaria:

In [12]:
CBA.head()

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
0,2016-04-01,1514.53,1358.29,1371.62,1333.91,1514.96,1556.96
1,2016-05-01,1561.35,1398.20,1404.27,1369.37,1562.75,1604.30
2,2016-06-01,1614.32,1445.22,1447.63,1413.77,1614.33,1661.42
3,2016-07-01,1666.48,1494.04,1496.21,1458.24,1660.19,1713.67
4,2016-08-01,1675.05,1496.09,1501.91,1459.38,1662.99,1723.86

In [13]:
CBA.tail()

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
112,2025-08-01,168456.04,150019.85,149802.94,145932.54,165643.09,172540.84
113,2025-09-01,170788.46,152803.20,152566.11,148800.44,168519.55,175412.47
114,2025-10-01,176150.29,157636.84,157679.95,153475.78,174130.91,181342.77
115,2025-11-01,183289.46,163650.50,164584.23,159191.14,181196.12,189380.65
116,2025-12-01,190780.09,169325.29,171065.04,164555.21,188144.43,197032.47

In [14]:
CBT.head()

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
0,2016-04-01,3665.17,3504.40,3099.86,2987.95,3666.21,4281.63
1,2016-05-01,3825.30,3649.31,3229.82,3122.17,3828.74,4459.96
2,2016-06-01,3938.94,3757.58,3315.07,3209.27,3938.96,4602.13
3,2016-07-01,4032.88,3854.62,3396.40,3281.04,4017.66,4712.59
4,2016-08-01,4036.87,3844.95,3394.32,3269.01,4007.81,4723.38

In [15]:
CBT.tail()

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
112,2025-08-01,375656.97,355547.04,313088.14,302080.36,369384.09,436528.33
113,2025-09-01,380858.27,363671.62,318863.17,308016.91,375798.60,445547.67
114,2025-10-01,392815.15,375175.68,329551.10,317694.86,388311.93,458797.21
115,2025-11-01,406902.60,387851.69,342335.20,327933.75,402255.39,477239.24
116,2025-12-01,423531.80,399607.68,355815.28,338983.73,417680.63,496521.82

In [11]:
pobreza_indigencia

,indice_tiempo,canasta_basica_alimentaria,inversa_coeficiente_engel,canasta_basica_total,linea_indigencia,linea_pobreza
0,2016-04-01,1514.53,2.42,3663.66,4679.9100,1.132071e+04
1,2016-05-01,1561.35,2.45,3830.77,4824.5600,1.183708e+04
2,2016-06-01,1614.32,2.44,3942.67,4988.2500,1.218284e+04
3,2016-07-01,1666.48,2.42,4033.76,5149.4100,1.246433e+04
4,2016-08-01,1675.05,2.41,4041.87,5175.9200,1.248937e+04
...,...,...,...,...,...,...
118,2026-02-01,208442.85,2.17,452320.98,644088.4100,1.397672e+06
119,2026-03-01,212948.52,2.18,464227.77,658010.9268,1.434464e+06
120,2026-04-01,215227.62,2.21,475653.04,665053.3458,1.469768e+06
121,2026-05-01,220467.99,2.20,485029.58,681246.0891,1.498741e+06
122,2026-06-01,223253.29,2.22,495622.30,689852.6661,1.531473e+06

### Estan correctos de estructura

## <center> Cargamos IPC

In [16]:
hojas_ipc = pd.read_excel(IPC_DIR/"ipc_nacional.xlsx", sheet_name=None)

In [17]:
hojas_ipc

{'Indice':                Unnamed: 1  Unnamed: 2  \
 0   NaN            INDICE         NaN
 1   NaN               NaN         NaN
 2   NaN  Cuadros -Precios         NaN
 3   NaN               NaN         NaN
 4   NaN             4.1.1         NaN
 ..   ..               ...         ...
 124 NaN              4.36         NaN
 125 NaN               NaN         NaN
 126 NaN              4.37         NaN
 127 NaN               NaN         NaN
 128 NaN              4.38         NaN

                                             Unnamed: 3
 0                                                  NaN
 1                                                  NaN
 2                                                  NaN
 3                                                  NaN
 4                                    IPC Nivel General
 ..                                                 ...
 124  Índice de precios al consumidor Tucumán. Nivel...
 125                                                NaN
 126  Índice de precios al consumidor CABA.  Nivel G...
 127                                                NaN
 128  Índice de precios al consumidor Chaco.  Nivel ...

 [129 rows x 4 columns],
 '4.1.1 IPC NG':         Unnamed: 0       CUADRO 4.1.1.   \
 0              NaN    IPC Nivel General
 1              NaN  Base Dic-2016 = 100
 2              NaN                  NaN
 3              NaN                  NaN
 4          Período             NACIONAL
 ..             ...                  ...
 217  Fuente: INDEC             Pampeana
 218            NaN                  NEA
 219            NaN                  NOA
 220            NaN                 Cuyo
 221            NaN            Patagonia

                                             Unnamed: 2 Unnamed: 3 Unnamed: 4  \
 0                                                  NaN        NaN        NaN
 1                                                  NaN        NaN        NaN
 2                                                  NaN        NaN        NaN
 3                                                  NaN        NaN        NaN
 4                                                  GBA   PAMPEANA        NEA
 ..                                                 ...        ...        ...
 217  Buenos Aires, Córdoba, Entre Ríos, La Pampa y ...        NaN        NaN
 218              Chaco, Corrientes, Formosa y Misiones        NaN        NaN
 219  Catamarca, Jujuy, La Rioja, Salta, Santiago de...        NaN        NaN
 220                       Mendoza, San Juan y San Luis        NaN        NaN
 221  Chubut, Neuquén, Río Negro, Santa Cruz y Tierr...        NaN        NaN

     Unnamed: 5 Unnamed: 6     Índice  Unnamed: 8                   Unnamed: 9  \
 0          NaN        NaN        NaN         NaN                          NaN
 1          NaN        NaN        NaN         NaN                          NaN
 2          NaN        NaN        NaN         NaN   Tasas de Variación MENSUAL
 3          NaN        NaN        NaN         NaN                          NaN
 4          NOA       CUYO  PATAGONIA         NaN                     NACIONAL
 ..         ...        ...        ...         ...                          ...
 217        NaN        NaN        NaN         NaN                          NaN
 218        NaN        NaN        NaN         NaN                          NaN
 219        NaN        NaN        NaN         NaN                          NaN
 220        NaN        NaN        NaN         NaN                          NaN
 221        NaN        NaN        NaN         NaN                          NaN

      ... Unnamed: 15 Unnamed: 16  \
 0    ...         NaN         NaN
 1    ...         NaN         NaN
 2    ...         NaN         NaN
 3    ...         NaN         NaN
 4    ...   PATAGONIA         NaN
 ..   ...         ...         ...
 217  ...         NaN         NaN
 218  ...         NaN         NaN
 219  ...         NaN         NaN
 220  ...         NaN         NaN
 221  ...         NaN         NaN

                                            Unnamed: 17 Unnamed: 18  \
 0                                                  NaN         NaN
 1                                                  NaN         NaN
 2    Tasas de Variación ACUMULADA desde diciembre d...         NaN
 3                                                  NaN         NaN
 4                                              Período    NACIONAL
 ..                                                 ...         ...
 217                                                NaN         NaN
 218                                                NaN         NaN
 219                                                NaN         NaN
 220                                                NaN         NaN
 221                                                NaN         NaN

     Unnamed: 19 Unnamed: 20  Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
 0           NaN         NaN          NaN         NaN         NaN         NaN
 1           NaN         NaN          NaN         NaN         NaN         NaN
 2           NaN         NaN          NaN         NaN         NaN         NaN
 3           NaN         NaN          NaN         NaN         NaN         NaN
 4           GBA    PAMPEANA          NEA         NOA        CUYO   PATAGONIA
 ..          ...         ...          ...         ...         ...         ...
 217         NaN         NaN          NaN         NaN         NaN         NaN
 218         NaN         NaN          NaN         NaN         NaN         NaN
 219         NaN         NaN          NaN         NaN         NaN         NaN
 220         NaN         NaN          NaN         NaN         NaN         NaN
 221         NaN         NaN          NaN         NaN         NaN         NaN

 [222 rows x 25 columns],
 '4.1.2 IPC Capitulos':               Unnamed: 0         CUADRO 4.1.2 Unnamed: 2 Unnamed: 3  \
 0                    NaN        IPC Capítulos        NaN        NaN
 1                    NaN  Base Dic-2016 = 100        NaN        NaN
 2                    NaN                  NaN        NaN        NaN
 3                    NaN                  NaN        NaN        NaN
 4                Período             NACIONAL        NaN        NaN
 ..                   ...                  ...        ...        ...
 201  2026-04-01 00:00:00            12194.882  7969.9785  8326.6612
 202  2026-05-01 00:00:00           12494.9767  8033.2555  8350.2424
 203  2026-06-01 00:00:00           12657.4575   8201.663   8384.717
 204                  NaN                  NaN        NaN        NaN
 205        Fuente: INDEC                  NaN        NaN        NaN

      Unnamed: 4 Unnamed: 5  Unnamed: 6      Índice  Unnamed: 8  Unnamed: 9  \
 0           NaN        NaN         NaN         NaN         NaN         NaN
 1           NaN        NaN         NaN         NaN         NaN         NaN
 2           NaN        NaN         NaN         NaN         NaN         NaN
 3           NaN        NaN         NaN         NaN         NaN         NaN
 4           NaN        NaN         NaN         NaN         NaN         NaN
 ..          ...        ...         ...         ...         ...         ...
 201  12470.6962   9182.794  12508.3899   12091.593  10478.7314   9860.2728
 202  12790.0776  9312.2108  12832.0291  12330.5017  10838.4277  10132.3705
 203  13213.1497  9455.0367   13200.749  12531.7975  10933.5551   10556.461
 204         NaN        NaN         NaN         NaN         NaN         NaN
 205         NaN        NaN         NaN         NaN         NaN         NaN

      ... Unnamed: 81 Unnamed: 82 Unnamed: 83  Unnamed: 84 Unnamed: 85  \
 0    ...         NaN         NaN         NaN          NaN         NaN
 1    ...         NaN         NaN         NaN          NaN         NaN
 2    ...         NaN         NaN         NaN          NaN         NaN
 3    ...         NaN         NaN         NaN          NaN         NaN
 4    ...         NaN         NaN         NaN          NaN         NaN
 ..   ...         ...         ...         ...          ...         ...
 201  ...   8251.8746  15743.9522   9633.8748    12983.163  13235.6935
 202  ...   8411.5366  15825.4092   9762.3573   13283.7101   13405.945
 203  ...   8484.8172  16287.3709    9903.758   13638.3732  13499.0961
 204  ...         NaN         NaN         NaN          NaN         NaN
 205  ...         NaN         NaN         NaN          NaN         NaN

     Unnamed: 86 Unnamed: 87 Unnamed: 88 Unnamed: 89 Unnamed: 90
 0           NaN         NaN         NaN         NaN         NaN
 1           NaN         NaN         NaN         NaN         NaN
 2           NaN         NaN         NaN         NaN         NaN
 3           NaN         NaN         NaN         NaN         NaN
 4           NaN         NaN         NaN         NaN         NaN
 ..          ...         ...         ...         ...         ...
 201   9028.6759   8782.6691  10129.9638  13938.8772   11454.792
 202   9358.1231    9002.004  10430.9854  14151.9307  11670.0607
 203   9390.2227   9290.3322  10622.8039  14307.4479  11966.5646
 204         NaN         NaN         NaN         NaN         NaN
 205         NaN         NaN         NaN         NaN         NaN

 [206 rows x 91 columns],
 'Hoja1': Empty DataFrame
 Columns: []
 Index: [],
 '4.1.3 IPC Bs Ss':               Unnamed: 0            CUADRO 4.1.3  Unnamed: 2  Unnamed: 3  \
 0                    NaN  IPC Bienes y Servicios         NaN         NaN
 1                    NaN     Base Dic-2016 = 100         NaN         NaN
 2                    NaN                     NaN         NaN         NaN
 3                    NaN                     NaN         NaN         NaN
 4                Período                NACIONAL         NaN         NaN
 ..                   ...                     ...         ...         ...
 201  2026-04-01 00:00:00              11289.6872  11566.6891         NaN
 202  2026-05-01 00:00:00              11514.1432  11856.0739         NaN
 203  2026-06-01 00:00:00              11669.7596  12197.4173         NaN
 204                  NaN                     NaN         NaN         NaN
 205        Fuente: INDEC                     NaN         NaN         NaN

      Unnamed: 4  Unnamed: 5  Unnamed: 6      Índice  Unnamed: 8  Unnamed: 9  \
 0           NaN         NaN         NaN         NaN         NaN         NaN
 1           NaN         NaN         NaN         NaN         NaN         NaN
 2           NaN         NaN         NaN         NaN         NaN         NaN
 3           NaN         NaN         NaN         NaN         NaN         NaN
 4           GBA         NaN         NaN    PAMPEANA         NaN         NaN
 ..          ...         ...         ...         ...         ...         ...
 201   11316.554  11365.7347         NaN  11357.7692   11265.729         NaN
 202  11559.1257  11646.2193         NaN  11566.4477  11534.3387         NaN
 203  11699.8877  11972.9357         NaN  11732.9244   11930.693         NaN
 204         NaN         NaN         NaN         NaN         NaN         NaN
 205         NaN         NaN         NaN         NaN         NaN         NaN

      ... Unnamed: 146 Unnamed: 147  Unnamed: 148 Unnamed: 149 Unnamed: 150  \
 0    ...          NaN          NaN           NaN          NaN          NaN
 1    ...          NaN          NaN           NaN          NaN          NaN
 2    ...          NaN          NaN           NaN          NaN          NaN
 3    ...          NaN          NaN           NaN          NaN          NaN
 4    ...          NaN          NaN           NaN          NaN          NaN
 ..   ...          ...          ...           ...          ...          ...
 201  ...          NaN          NaN           NaN          NaN          NaN
 202  ...          NaN          NaN           NaN          NaN          NaN
 203  ...          NaN          NaN           NaN          NaN          NaN
 204  ...          NaN          NaN           NaN          NaN          NaN
 205  ...          NaN          NaN           NaN          NaN          NaN

      Unnamed: 151 Unnamed: 152 Unnamed: 153  Unnamed: 154 Unnamed: 155
 0             NaN          NaN          NaN           NaN          NaN
 1             NaN          NaN          NaN           NaN          NaN
 2             NaN          NaN          NaN           NaN          NaN
 3             NaN          NaN          NaN           NaN          NaN
 4             NaN          NaN          NaN           NaN          NaN
 ..            ...          ...          ...           ...          ...
 201           NaN          NaN          NaN           NaN          NaN
 202           NaN          NaN          NaN           NaN          NaN
 203           NaN          NaN          NaN           NaN          NaN
 204           NaN          NaN          NaN           NaN          NaN
 205           NaN          NaN          NaN           NaN          NaN

 [206 rows x 156 columns],
 '4.1.4 IPC Incidencia Cap':               Unnamed: 0                                       CUADRO 4.1.4  \
 0                    NaN  IPC Incidencia de los capítulos en el nivel ge...
 1                    NaN                                Base Dic-2016 = 100
 2                    NaN  4.1. Incidencia absoluta y acumulada mensual p...
 3                    NaN                                                NaN
 4                Período                                           G. B. A.
 ..                   ...                                                ...
 113  2026-04-01 00:00:00                                             0.0032
 114  2026-05-01 00:00:00                                             0.0071
 115  2026-06-01 00:00:00                                             0.0031
 116                  NaN                                                NaN
 117        Fuente: INDEC                                                NaN

     Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  Índice Unnamed: 8  \
 0          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 1          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 2          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 3          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 4          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 ..         ...        ...        ...        ...        ...     ...        ...
 113     0.0005     0.0028     0.0049     0.0016     0.0025  0.0043     0.0011
 114     0.0002    -0.0002     0.0019     0.0006     0.0025  0.0029      0.001
 115     0.0005     0.0001     0.0041     0.0008      0.003  0.0017     0.0001
 116        NaN        NaN        NaN        NaN        NaN     NaN        NaN
 117        NaN        NaN        NaN        NaN        NaN     NaN        NaN

     Unnamed: 9  ... Unnamed: 146 Unnamed: 147 Unnamed: 148  Unnamed: 149  \
 0          NaN  ...          NaN          NaN          NaN           NaN
 1          NaN  ...          NaN          NaN          NaN           NaN
 2          NaN  ...          NaN          NaN          NaN           NaN
 3          NaN  ...          NaN          NaN          NaN           NaN
 4          NaN  ...          NaN          NaN          NaN           NaN
 ..         ...  ...          ...          ...          ...           ...
 113      0.001  ...       0.0055        0.026       0.0043        0.0065
 114      0.002  ...       0.0075       0.0268       0.0051        0.0079
 115     0.0027  ...       0.0084       0.0313        0.006        0.0097
 116        NaN  ...          NaN          NaN          NaN           NaN
 117        NaN  ...          NaN          NaN          NaN           NaN

     Unnamed: 150 Unnamed: 151 Unnamed: 152 Unnamed: 153 Unnamed: 154  \
 0            NaN          NaN          NaN          NaN          NaN
 1            NaN          NaN          NaN          NaN          NaN
 2            NaN          NaN          NaN          NaN          NaN
 3            NaN          NaN          NaN          NaN          NaN
 4            NaN          NaN          NaN          NaN          NaN
 ..           ...          ...          ...          ...          ...
 113       0.0189       0.0029       0.0043        0.003       0.0063
 114       0.0211        0.004       0.0059       0.0036       0.0074
 115       0.0224       0.0041       0.0081        0.004       0.0081
 116          NaN          NaN          NaN          NaN          NaN
 117          NaN          NaN          NaN          NaN          NaN

     Unnamed: 155
 0            NaN
 1            NaN
 2            NaN
 3            NaN
 4            NaN
 ..           ...
 113       0.0029
 114       0.0035
 115       0.0044
 116          NaN
 117          NaN

 [118 rows x 156 columns],
 '4.1.5 IPC Incidencia Bs Ss':               Unnamed: 0                                       CUADRO 4.1.5  \
 0                    NaN  IPC Incidencia de los bienes y servicios en el...
 1                    NaN                                Base Dic-2016 = 100
 2                    NaN  5.1. Incidencia absoluta por región y por bien...
 3                    NaN                                                NaN
 4                Período                                           NACIONAL
 ..                   ...                                                ...
 114  2026-05-01 00:00:00                                           0.012979
 115  2026-06-01 00:00:00                                           0.008939
 116                  NaN                                                NaN
 117                  NaN                                                NaN
 118        Fuente: INDEC                                                NaN

     Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  Índice Unnamed: 8  \
 0          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 1          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 2          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 3          NaN        NaN        NaN        NaN        NaN     NaN        NaN
 4          NaN     G.B.A.        NaN   PAMPEANA        NaN     NEA        NaN
 ..         ...        ...        ...        ...        ...     ...        ...
 114   0.008548     0.0127     0.0101     0.0129     0.0071  0.0157     0.0108
 115   0.009955     0.0072     0.0115     0.0101     0.0102  0.0124     0.0069
 116        NaN        NaN        NaN        NaN        NaN     NaN        NaN
 117        NaN        NaN        NaN        NaN        NaN     NaN        NaN
 118        NaN        NaN        NaN        NaN        NaN     NaN        NaN

     Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14
 0          NaN         NaN         NaN         NaN         NaN         NaN
 1          NaN         NaN         NaN         NaN         NaN         NaN
 2          NaN         NaN         NaN         NaN         NaN         NaN
 3          NaN         NaN         NaN         NaN         NaN         NaN
 4          NOA         NaN        CUYO         NaN   PATAGONIA         NaN
 ..         ...         ...         ...         ...         ...         ...
 114     0.0136      0.0074      0.0128      0.0079      0.0126      0.0043
 115     0.0104      0.0063      0.0111      0.0048       0.009      0.0072
 116        NaN         NaN         NaN         NaN         NaN         NaN
 117        NaN         NaN         NaN         NaN         NaN         NaN
 118        NaN         NaN         NaN         NaN         NaN         NaN

 [119 rows x 15 columns],
 '4.1.6 IPC Categorias':               Unnamed: 0         CUADRO 4.1.6 Unnamed: 2  Unnamed: 3  \
 0                    NaN       IPC Categorías        NaN         NaN
 1                    NaN  Base Dic-2016 = 100        NaN         NaN
 2                    NaN                  NaN        NaN         NaN

In [18]:
nombres_hojas_ipc = list(hojas_ipc.keys())
print(f"Hojas encontradas en el archivo de IPC: {nombres_hojas_ipc}\n")

Hojas encontradas en el archivo de IPC: ['Indice', '4.1.1 IPC NG', '4.1.2 IPC Capitulos', 'Hoja1', '4.1.3 IPC Bs Ss', '4.1.4 IPC Incidencia Cap', '4.1.5 IPC Incidencia Bs Ss', '4.1.6 IPC Categorias', '4.1.7 Incidencia Cat', '4.1.8 IPC precios canasta', '4.2.1', '4.2.2', '4.2.3', '4.2.4', '4.2.5', '4.3 IPIM', '4.3.1 IPIM 4 dígitos', '4.4 IPIB', '4.4.1 IPIB 4 dígitos', '4.5 IPP', '4.5.1 IPP 4 dígitos', '4.6 ICC', '4.7.1', '4.7.2', '4.8.1 ', '4.8.2', '4.8.3', '4.9.1', '4.9.2', '4.9.3', '4.9.4', '4.10', '4.11', '4.12', '4.13.1', '4.13.2', '4.14', '4.15.1', '4.15.2', '4.16.2', '4.16.1', '4.16.3', '4.16.4', '4.17', '4.18', '4.19', '4.20', '4.21', '4.22', '4.23', '4.24', '4.25', '4.26', '4.27', '4.28', '4.29', '4.30', '4.31', '4.32', '4.33 San Juan', '4.34 Jujuy', '4.35 Chaco serie histórica', '4.36 Tucumán', '4.37 CABA', '4.38 Chaco']

In [19]:
hojas_ipc["4.1.1 IPC NG"].tail(20)

,Unnamed: 0,CUADRO 4.1.1.,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
202,2025-07-01 00:00:00,9023.973,9016.5562,9016.3238,8905.132,9073.9428,9074.6511,9141.623,NaN,0.019017,...,0.021419,NaN,2025-07-01 00:00:00,0.172857,0.174218,0.172889,0.150942,0.176426,0.165109,0.184595
203,2025-08-01 00:00:00,9193.2441,9185.3068,9182.3487,9055.1527,9252.4989,9266.2277,9320.3353,NaN,0.018758,...,0.019549,NaN,2025-08-01 00:00:00,0.194858,0.196194,0.194487,0.170331,0.199576,0.189706,0.207753
204,2025-09-01 00:00:00,9384.0922,9377.7681,9366.761,9217.6682,9455.5666,9465.5075,9543.6369,NaN,0.02076,...,0.023959,NaN,2025-09-01 00:00:00,0.219662,0.221258,0.218476,0.191336,0.225903,0.215292,0.236689
205,2025-10-01 00:00:00,9603.8623,9602.5137,9584.145,9419.0224,9657.7445,9687.3328,9774.0954,NaN,0.023419,...,0.024148,NaN,2025-10-01 00:00:00,0.248226,0.250527,0.246754,0.21736,0.252116,0.243772,0.266552
206,2025-11-01 00:00:00,9841.3581,9840.8457,9821.3638,9642.9016,9879.6088,9960.8437,10001.4949,NaN,0.024729,...,0.023266,NaN,2025-11-01 00:00:00,0.279094,0.281565,0.277613,0.246295,0.28088,0.278889,0.296019
207,2025-12-01 00:00:00,10121.3715,10115.6707,10107.6074,9968.3824,10137.067,10255.4297,10258.6285,NaN,0.028453,...,0.02571,NaN,2025-12-01 00:00:00,0.315488,0.317355,0.314849,0.288362,0.314259,0.316711,0.329339
208,2026-01-01 00:00:00,10413.0309,10395.7458,10400.4968,10350.7115,10425.8507,10561.6315,10554.0348,NaN,0.028816,...,0.028796,NaN,2026-01-01 00:00:00,0.028816,0.027687,0.028977,0.038354,0.028488,0.029858,0.028796
209,2026-02-01 00:00:00,10714.6255,10667.6896,10714.2389,10676.7516,10795.0756,10921.6567,10868.5551,NaN,0.028963,...,0.029801,NaN,2026-02-01 00:00:00,0.058614,0.054571,0.060017,0.071062,0.064911,0.064963,0.059455
210,2026-03-01 00:00:00,11077.0608,11031.5404,11065.4568,11119.3596,11221.7466,11271.7383,11137.8047,NaN,0.033826,...,0.024773,NaN,2026-03-01 00:00:00,0.094423,0.09054,0.094765,0.115463,0.107001,0.0991,0.085701
211,2026-04-01 00:00:00,11363.0904,11336.5576,11330.2697,11423.3251,11506.6342,11511.107,11429.5989,NaN,0.025822,...,0.026199,NaN,2026-04-01 00:00:00,0.122683,0.120693,0.120965,0.145956,0.135105,0.12244,0.114145
212,2026-05-01 00:00:00,11607.3937,11594.5499,11556.8543,11725.5958,11747.5318,11750.0933,11622.7473,NaN,0.0215,...,0.016899,NaN,2026-05-01 00:00:00,0.14682,0.146197,0.143382,0.176279,0.158869,0.145744,0.132973
213,2026-06-01 00:00:00,11826.4103,11810.9464,11792.013,11951.8421,11943.1627,11937.3726,11811.1393,NaN,0.018869,...,0.016209,NaN,2026-06-01 00:00:00,0.168459,0.167589,0.166647,0.198975,0.178167,0.164005,0.151337
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Fuente: INDEC,Pampeana,"Buenos Aires, Córdoba, Entre Ríos, La Pampa y ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,NaN,NEA,"Chaco, Corrientes, Formosa y Misiones",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NOA,"Catamarca, Jujuy, La Rioja, Salta, Santiago de...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,NaN,Cuyo,"Mendoza, San Juan y San Luis",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,NaN,Patagonia,"Chubut, Neuquén, Río Negro, Santa Cruz y Tierr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_ipc_general = hojas_ipc["4.1.1 IPC NG"].iloc[:, :7].copy()
df_ipc_general.columns = df_ipc_general.iloc[4]
# 2. Cortar el DataFrame para dejar solo los datos (de la fila 2 en adelante)
df_ipc_general = df_ipc_general.iloc[4:-8].reset_index(drop=True)
df_final = df_ipc_general.loc[:, df_ipc_general.columns.notna()]
df_final

4,Período,NACIONAL,GBA,PAMPEANA,NEA,NOA,CUYO
0,Período,NACIONAL,GBA,PAMPEANA,NEA,NOA,CUYO
1,145.1_INDICE_TIEMPO_DICI_T_13,145.1_IPC_NG_NACNAL_DICI_T_15,145.1_IPC_NG_GBAGBA_DICI_T_10,145.1_IPC_NG_PAMANA_DICI_T_15,145.1_IPC_NG_NEANEA_DICI_T_10,145.1_IPC_NG_NOANOA_DICI_T_10,145.1_IPC_NG_CUYUYO_DICI_T_11
2,I.17,103.806467,103.794733,103.711967,103.707467,104.122633,103.632133
3,II.17,110.448167,110.505433,110.1325,110.240233,111.430333,111.063167
4,III.17,115.579667,115.829533,115.321167,114.741733,115.9341,115.721167
...,...,...,...,...,...,...,...
205,2026-02-01 00:00:00,10714.6255,10667.6896,10714.2389,10676.7516,10795.0756,10921.6567
206,2026-03-01 00:00:00,11077.0608,11031.5404,11065.4568,11119.3596,11221.7466,11271.7383
207,2026-04-01 00:00:00,11363.0904,11336.5576,11330.2697,11423.3251,11506.6342,11511.107
208,2026-05-01 00:00:00,11607.3937,11594.5499,11556.8543,11725.5958,11747.5318,11750.0933
209,2026-06-01 00:00:00,11826.4103,11810.9464,11792.013,11951.8421,11943.1627,11937.3726

In [21]:
df_final[45:100]

4,Período,NACIONAL,GBA,PAMPEANA,NEA,NOA,CUYO
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,145.3_ICETIEMPO_DICI_M_13,145.3_INGNACNAL_DICI_M_15,145.3_INGGBAGBA_DICI_M_10,145.3_INGPAMANA_DICI_M_15,145.3_INGNEANEA_DICI_M_10,145.3_INGNOANOA_DICI_M_10,145.3_INGCUYUYO_DICI_M_11
95,2016-12-01 00:00:00,100,100,100,100,100,100
96,2017-01-01 00:00:00,101.5859,101.313,101.7874,101.6727,101.6014,101.7074
97,2017-02-01 00:00:00,103.6859,103.8085,103.5312,103.4617,103.7115,103.2652
98,2017-03-01 00:00:00,106.1476,106.2627,105.8173,105.988,107.055,105.9238
99,2017-04-01 00:00:00,108.9667,109.0613,108.6912,108.3473,109.9626,109.4506

### Vemos la tabla esta dividad en dos, primero estan los valore del IPC de forma trimestral (filas 0 a 44), luego desde la fila 95 hasta terminar la tabla, los valores del IPC pero de forma mensual por año. Nos quedamos por simplicidad y mayor capacidad de transformacion con los datos mensuales.

In [22]:
df_IPC_general_mensual = df_final[94:].copy()
df_IPC_general_mensual = df_IPC_general_mensual.iloc[1:].reset_index(drop=True)

In [23]:
df_IPC_general_mensual

4,Período,NACIONAL,GBA,PAMPEANA,NEA,NOA,CUYO
0,2016-12-01 00:00:00,100,100,100,100,100,100
1,2017-01-01 00:00:00,101.5859,101.313,101.7874,101.6727,101.6014,101.7074
2,2017-02-01 00:00:00,103.6859,103.8085,103.5312,103.4617,103.7115,103.2652
3,2017-03-01 00:00:00,106.1476,106.2627,105.8173,105.988,107.055,105.9238
4,2017-04-01 00:00:00,108.9667,109.0613,108.6912,108.3473,109.9626,109.4506
...,...,...,...,...,...,...,...
110,2026-02-01 00:00:00,10714.6255,10667.6896,10714.2389,10676.7516,10795.0756,10921.6567
111,2026-03-01 00:00:00,11077.0608,11031.5404,11065.4568,11119.3596,11221.7466,11271.7383
112,2026-04-01 00:00:00,11363.0904,11336.5576,11330.2697,11423.3251,11506.6342,11511.107
113,2026-05-01 00:00:00,11607.3937,11594.5499,11556.8543,11725.5958,11747.5318,11750.0933
114,2026-06-01 00:00:00,11826.4103,11810.9464,11792.013,11951.8421,11943.1627,11937.3726

### <center>Carguemos ademas los precios de los alimentos de la canasta basica IPC:

In [24]:
dfs_regiones = {}

# 2. Inicializar los límites del bloque de columnas
columnas_por_region = 15
bottom = 0
top = columnas_por_region

regiones = ["GBA", "PAMPEANA", "NEA", "NOA", "CUYO", "PATAGONIA"]

for region in regiones:
    # 3. Crear la clave dinámica para el diccionario
    nombre_clave = f"df_ipc_canasta_{region}"
    
    # 4. Extraer el bloque de COLUMNAS correspondiente (todas las filas ":")
    dfs_regiones[nombre_clave] = hojas_ipc["4.1.8 IPC precios canasta"].iloc[:, bottom:top].copy()
    
    # 5. Imprimir para verificar el resultado
    print(f"--- {nombre_clave} (Columnas {bottom} a {top}) ---")
    print(dfs_regiones[nombre_clave])
    
    # 6. Desplazar los límites exactamente 14 columnas hacia adelante
    bottom = top
    top += columnas_por_region

--- df_ipc_canasta_GBA (Columnas 0 a 15) ---
              Unnamed: 0                                       CUADRO 4.1.8  \
0                    NaN  Precios al consumidor de un conjunto de elemen...
1                    NaN                                                NaN
2                    NaN  8.1. Precios al consumidor de un conjunto de e...
3                    NaN                                          En pesos
4                Período                                           G. B. A.
..                   ...                                                ...
113  2026-04-01 00:00:00                                            4383.37
114  2026-05-01 00:00:00                                            4471.54
115  2026-06-01 00:00:00                                            4652.79
116                  NaN                                                NaN
117        Fuente: INDEC                                                NaN

    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6   Índice  \
0          NaN        NaN        NaN        NaN        NaN      NaN
1          NaN        NaN        NaN        NaN        NaN      NaN
2          NaN        NaN        NaN        NaN        NaN      NaN
3          NaN        NaN        NaN        NaN        NaN      NaN
4          NaN        NaN        NaN        NaN        NaN      NaN
..         ...        ...        ...        ...        ...      ...
113     969.13    1713.73    1611.65   10439.61    4782.03  6241.57
114     977.06     1750.9    1629.13   10402.23    4794.21  6476.25
115     991.11    1783.17    1685.05   10623.71    4820.82  6628.02
116        NaN        NaN        NaN        NaN        NaN      NaN
117        NaN        NaN        NaN        NaN        NaN      NaN

    Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0          NaN        NaN         NaN         NaN         NaN         NaN
1          NaN        NaN         NaN         NaN         NaN         NaN
2          NaN        NaN         NaN         NaN         NaN         NaN
3          NaN        NaN         NaN         NaN         NaN         NaN
4          NaN        NaN         NaN         NaN         NaN         NaN
..         ...        ...         ...         ...         ...         ...
113    1819.68    3931.74     1305.47      1432.8     1974.77     1385.36
114    1918.61     3875.5     1473.32     1495.66     2053.23      1410.3
115    1926.42    3881.27     1544.25     1516.46     2094.51      1411.3
116        NaN        NaN         NaN         NaN         NaN         NaN
117        NaN        NaN         NaN         NaN         NaN         NaN

    Unnamed: 14
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
113     1403.58
114     1458.42
115     1469.35
116         NaN
117         NaN

[118 rows x 15 columns]
--- df_ipc_canasta_PAMPEANA (Columnas 15 a 30) ---
     Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20  \
0            NaN         NaN         NaN         NaN         NaN         NaN
1            NaN         NaN         NaN         NaN         NaN         NaN
2            NaN         NaN         NaN         NaN         NaN         NaN
3            NaN         NaN         NaN         NaN         NaN         NaN
4            NaN    PAMPEANA         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
113          NaN     3310.74     1020.53     2021.44     1525.12    11007.65
114          NaN     3406.11     1049.57     2036.52     1539.27     11240.6
115          NaN     3489.14     1073.47     2071.73     1561.09    11355.66
116          NaN         NaN         NaN         NaN         NaN         NaN
117          NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
113      5079.2     6450.03     1895.73     3919.63     1311.82     1429.04
114     5054.13     6718.87     1987.76     3920.77     1475.87     1488.19
115     5029.98     6850.26     2043.37     3939.62     1540.44     1520.27
116         NaN         NaN         NaN         NaN         NaN         NaN
117         NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 27 Unnamed: 28 Unnamed: 29
0           NaN         NaN         NaN
1           NaN         NaN         NaN
2           NaN         NaN         NaN
3           NaN         NaN         NaN
4           NaN         NaN         NaN
..          ...         ...         ...
113      2380.5     1395.79     1401.21
114     2455.49     1404.94     1450.09
115     2550.13     1412.34     1481.63
116         NaN         NaN         NaN
117         NaN         NaN         NaN

[118 rows x 15 columns]
--- df_ipc_canasta_NEA (Columnas 30 a 45) ---
     Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 34 Unnamed: 35  \
0            NaN         NaN         NaN         NaN         NaN         NaN
1            NaN         NaN         NaN         NaN         NaN         NaN
2            NaN         NaN         NaN         NaN         NaN         NaN
3            NaN         NaN         NaN         NaN         NaN         NaN
4            NaN       N E A         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
113          NaN     2319.36       950.5     1664.94     1194.05    10771.23
114          NaN     2403.31      981.87     1689.91      1204.4    10665.68
115          NaN     2469.93      1010.4     1686.65      1192.9    10946.65
116          NaN         NaN         NaN         NaN         NaN         NaN
117          NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 36 Unnamed: 37 Unnamed: 38 Unnamed: 39 Unnamed: 40 Unnamed: 41  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
113     4703.87     6381.26     1900.01     3406.91     1247.21     1386.48
114     4641.61     6539.49      2034.4     3403.63     1399.04      1442.3
115     4631.33     6692.88     2086.96     3392.69     1467.27     1477.22
116         NaN         NaN         NaN         NaN         NaN         NaN
117         NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 42 Unnamed: 43 Unnamed: 44
0           NaN         NaN         NaN
1           NaN         NaN         NaN
2           NaN         NaN         NaN
3           NaN         NaN         NaN
4           NaN         NaN         NaN
..          ...         ...         ...
113     2232.16        1363     1324.78
114     2272.72     1393.77     1348.24
115     2376.96     1417.14     1389.31
116         NaN         NaN         NaN
117         NaN         NaN         NaN

[118 rows x 15 columns]
--- df_ipc_canasta_NOA (Columnas 45 a 60) ---
     Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
0            NaN         NaN         NaN         NaN         NaN         NaN
1            NaN         NaN         NaN         NaN         NaN         NaN
2            NaN         NaN         NaN         NaN         NaN         NaN
3            NaN         NaN         NaN         NaN         NaN         NaN
4            NaN       N O A         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
113          NaN     2688.63      928.47     1777.75     1271.18    12061.36
114          NaN     2779.38      949.92     1824.48     1290.59    11966.59
115          NaN     2878.71      987.96     1861.08     1303.22     12270.9
116          NaN         NaN         NaN         NaN         NaN         NaN
117          NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 51 Unnamed: 52 Unnamed: 53 Unnamed: 54 Unnamed: 55 Unnamed: 56  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
113     4691.88     6181.87     1837.68     3390.87     1112.33      1276.4
114     4691.89     6359.88     1924.78     3369.44     1310.61     1320.69
115     4671.65     6511.87     1975.25     3364.76     1329.52     1354.97
116         NaN         NaN         NaN         NaN         NaN         NaN
117         NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 57 Unnamed: 58 Unnamed: 59
0           NaN         NaN         NaN
1           NaN         NaN         NaN
2           NaN         NaN         NaN
3           NaN         NaN         NaN
4           NaN         NaN         NaN
..          ...         ...         ...
113     2193.31     1336.95        1324
114     2259.02     1355.98     1372.22
115      2358.3     1368.91     1402.04
116         NaN         NaN         NaN
117         NaN         NaN         NaN

[118 rows x 15 columns]
--- df_ipc_canasta_CUYO (Columnas 60 a 75) ---
     Unnamed: 60 Unnamed: 61 Unnamed: 62 Unnamed: 63 Unnamed: 64 Unnamed: 65  \
0            NaN         NaN         NaN         NaN         NaN         NaN
1            NaN         NaN         NaN         NaN         NaN         NaN
2            NaN         NaN         NaN         NaN         NaN         NaN
3            NaN         NaN         NaN         NaN         NaN         NaN
4            NaN        CUYO         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
113          NaN     2474.82      958.91     1927.52     1467.55    10038.99
114          NaN     2531.31      989.09     1934.74      1485.8    10009.19
115          NaN     2595.57     1002.68     1981.68     1504.82        9990
116          NaN         NaN         NaN         NaN         NaN         NaN
117          NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 66 Unnamed: 67 Unnamed: 68 Unnamed: 69 Unnamed: 70 Unnamed: 71  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
113     5173.15     6312.44      1925.5     3884.13     1258.64     1428.13
114     5112.54     6556.58     2042.45     3800.76     1411.18     1455.19
115     5082.17     6695.09     2057.76     3790.88     1591.71     1466.33
116         NaN         NaN         NaN         NaN         NaN         NaN
117         NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 72 Unnamed: 73 Unnamed: 74
0           NaN         NaN         NaN
1           NaN         NaN         NaN
2           NaN         NaN         NaN
3           NaN         NaN         NaN
4           NaN         NaN         NaN
..          ...         ...         ...
113     2046.75     1386.97     1393.04
114     2134.66     1395.19     1459.25
115     2216.93     1349.83     1496.56
116         NaN         NaN         NaN
117         NaN         NaN         NaN

[118 rows x 15 columns]
--- df_ipc_canasta_PATAGONIA (Columnas 75 a 90) ---
     Unnamed: 75 Unnamed: 76 Unnamed: 77 Unnamed: 78 Unnamed: 79 Unnamed: 80  \
0            NaN         NaN         NaN         NaN         NaN         NaN
1            NaN         NaN         NaN         NaN         NaN         NaN
2            NaN         NaN         NaN         NaN         NaN         NaN
3            NaN         NaN         NaN         NaN         NaN         NaN
4            NaN   PATAGONIA         NaN         NaN         NaN         NaN
..           ...         ...         ...         ...         ...         ...
113          NaN     4059.48     1176.15     2752.18     1800.18    13043.24
114          NaN     4099.65     1214.77     2795.31     1799.55    13022.38
115          NaN     4143.93     1213.05     2775.16     1852.81    13104.32
116          NaN         NaN         NaN         NaN         NaN         NaN
117          NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 81 Unnamed: 82 Unnamed: 83 Unnamed: 84 Unnamed: 85 Unnamed: 86  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           NaN         NaN         NaN         NaN         NaN         NaN
3           NaN         NaN         NaN         NaN         NaN         NaN
4           NaN         NaN         NaN         NaN         NaN         NaN
..          ...         ...         ...         ...         ...         ...
113     5100.03     6672.74     2096.16     4794.74     1792.12     1668.52
114     5177.48     6903.96     2225.13     4898.75     1897.38     1716.66
115     5133.67     7092.45     2245.05     4879.81     2087.64     1761.87
116         NaN         NaN         NaN         NaN         NaN         NaN
117         NaN         NaN         NaN         NaN         NaN         NaN

    Unnamed: 87 Unnamed: 88 Unnamed: 89
0           NaN         NaN         NaN
1           NaN         NaN         NaN
2           NaN         NaN         NaN
3           NaN         NaN         NaN
4           NaN         NaN         NaN
..          ...         ...         ...
113     4326.94     1553.77     1529.12
114     4553.14     1565.23     1568.72
115     4618.97     1575.29     1594.78
116         NaN         NaN         NaN
117         NaN         NaN         NaN

[118 rows x 15 columns]

In [25]:
df_GBA= dfs_regiones["df_ipc_canasta_GBA"]
df_GBA.head()

,Unnamed: 0,CUADRO 4.1.8,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Precios al consumidor de un conjunto de elemen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,8.1. Precios al consumidor de un conjunto de e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,En pesos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Período,G. B. A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_PAMPEANA = dfs_regiones["df_ipc_canasta_PAMPEANA"]
df_NEA = dfs_regiones["df_ipc_canasta_NEA"]
df_NOA = dfs_regiones["df_ipc_canasta_NOA"]
df_CUYO = dfs_regiones["df_ipc_canasta_CUYO"]
df_PATAGONIA = dfs_regiones["df_ipc_canasta_PATAGONIA"]

In [27]:
df_PATAGONIA[5:6]

,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
5,NaN,Pan francés (kg),Harina de trigo común 000 ...,Arroz blanco simple (kg),Fideos secos tipo guisero ...,Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet ...,Huevos de gallina (docena),Papa ...,Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)

In [28]:
df_NEA[5:6]

,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
5,NaN,Pan francés ...,Harina de trigo común 000 ...,Arroz blanco simple (kg),Fideos secos tipo guisero ...,Carne picada común (kg),Pollo entero ...,"Aceite de girasol (1,5 litros)",Leche fresca entera sachet ...,Huevos de gallina (docena),Papa (kg),Azúcar ...,Detergente líquido (750cc),Lavandina ...,Jabón de tocador (125 gr)

In [29]:
df_GBA[0:6]

,Unnamed: 0,CUADRO 4.1.8,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Precios al consumidor de un conjunto de elemen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,8.1. Precios al consumidor de un conjunto de e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,En pesos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Período,G. B. A.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Pan francés (kg),Harina de trigo común 000 ...,Arroz blanco simple (kg),Fideos secos tipo guisero ...,Carne picada común (kg),Pollo entero ...,"Aceite de girasol (1,5 litros)",Leche fresca entera sachet ...,Huevos de gallina (docena),Papa ...,Azúcar ...,Detergente líquido (750cc),Lavandina (10...,Jabón de tocador (125 gr)

In [30]:
df_NOA[5:6]

,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
5,NaN,Pan francés (kg),Harina de trigo común 000 ...,Arroz blanco simple (kg),Fideos secos tipo guisero ...,Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa ...,Azúcar ...,Detergente líquido (750cc),Lavandina ...,Jabón de tocador (125 gr)

In [31]:
df_ipc_canasta_GBA = format_df_IPC(df_GBA,7,-2, 5, df_GBA, False)
df_ipc_canasta_NEA = format_df_IPC(df_NEA,7,-2, 5, df_ipc_canasta_GBA, True)
df_ipc_canasta_NOA = format_df_IPC(df_NOA,7,-2, 5, df_ipc_canasta_GBA, True)
df_ipc_canasta_CUYO = format_df_IPC(df_CUYO,7,-2, 5, df_ipc_canasta_GBA, True)
df_ipc_canasta_PAMPEANA = format_df_IPC(df_PAMPEANA,7,-2, 5, df_ipc_canasta_GBA, True)
df_ipc_canasta_PATAGONIA = format_df_IPC(df_PATAGONIA,7,-2, 5, df_ipc_canasta_GBA, True)

In [32]:
ipc_canasta = {
    "GBA": df_ipc_canasta_GBA,
    "NEA": df_ipc_canasta_NEA,
    "NOA": df_ipc_canasta_NOA,
    "CUYO": df_ipc_canasta_CUYO,
    "PAMPEANA": df_ipc_canasta_PAMPEANA,
    "PATAGONIA": df_ipc_canasta_PATAGONIA,
}

## <center> Cargamos EPH

In [33]:
hojas_eph = pd.read_excel(EPH_DIR/'EPH.xlsx', sheet_name=None)
nombres_hojas_eph = list(hojas_eph.keys())
print(f"Hojas encontradas en el archivo de EPH: {nombres_hojas_eph}\n")

Hojas encontradas en el archivo de EPH: ['INDICE', 'EPH', 'TA 03-', 'TA 74-03', 'TE 03-', 'TE 74-03', 'TD 03-', 'TD 74-03', 'TS 03-', 'TS 74-03', 'TSD 03-', 'TSND 03-', 'EPH-Poblaciones', 'EAHU-Poblaciones', 'EAHU-Tasas', 'Expansion EPH a TU - 1991-2010', 'Expansion EPH a TU - Desde 2010', 'EIL - Sector', 'EIL - Aglo', 'EPH - Asal', 'EPH - Asal regiones', 'CGI-2016', 'CGI VABpb', 'CGI ManodeObra', 'CGI Puestos', 'CGI CostoSalarial', 'CGI Remun', 'CGI Remun netas', 'EIM', 'EIM Nuevo', 'IS', 'IS oct16=100', 'RIPTE', 'SMVM', 'HaberMin', 'AUH', 'CBA y CBT', 'CBA y CBT 2016', 'CBA y CBT Reg', 'CBA y CBT BA', 'EPH Puntual - PeI', 'LI - Hog', 'LI - Pers', 'LP - Hog', 'LP - Pers', 'DP', 'DP Deciles', 'OEDE Total', 'OEDE Asal rama', 'OEDE Asal prov', 'OEDE Puestos Sector', 'OEDE Puestos Rama', 'OEDE Remuneraciones', 'OEDE Remuneraciones Rama', 'Puestos x Sector', 'RT x Sector', 'RN x Sector', 'CS x Sector', 'Puestos x Prov', 'RT x Prov', 'RN x Prov', 'CS x Prov', 'SalariosInd-Indices 62-67', 'SalariosInd-var65-66', 'Salario peon60-75', 'Salario oficial60-75', 'Salario real Ind85-90', 'CostoNivelVida60-75', 'Hoja1']

### Cargamos los datos del Salario Minimo Vital y Movil:

In [34]:
df_SMVM_parcial = hojas_eph["SMVM"]
df_SMVM_parcial.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"Salario mínimo, vital y móvil",NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,En pesos corrientes,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,A partir de enero de 1965,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Período,|,NaN,NaN,Moneda,NaN,NaN,NaN
8,NaN,Mensual,Diario,Horario,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,57.1_IT_0_M_13,57.1_SMVMM_0_M_34,57.1_SMVMD_0_M_33,57.1_SMVMH_0_M_31,NaN,NaN,NaN,NaN
11,1965-01-01 00:00:00,9800,392,49,$ moneda nacional,NaN,NaN,NaN

In [35]:
df_SMVM_parcial.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice
743,2026-01-01 00:00:00,341000,13640,1705,$,NaN,NaN,NaN
744,2026-02-01 00:00:00,346800,13872.0,1734.0,$,NaN,NaN,NaN
745,2026-03-01 00:00:00,352400,14096.0,1762.0,$,NaN,NaN,NaN
746,2026-04-01 00:00:00,357800,14312.0,1789.0,$,NaN,NaN,NaN
747,2026-05-01 00:00:00,363000,14520.0,1815.0,$,NaN,NaN,NaN
748,2026-06-01 00:00:00,367800,14712.0,1839.0,$,NaN,NaN,NaN
749,2026-07-01 00:00:00,372400,14896.0,1862.0,$,NaN,NaN,NaN
750,2026-08-01 00:00:00,376600,15064.0,1883.0,$,NaN,NaN,NaN
751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
752,Fuente: Ministerio de Capital Humano.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df_SMVM = format_df("SMVM", hojas_eph, 8, -2, 8)
df_SMVM = df_SMVM.drop([0,1,2])
df_SMVM

8   Mensual   Diario Horario
3      9800      392      49
4      9800      392      49
5      9800      392      49
6      9800      392      49
7     11550      462   57.75
..      ...      ...     ...
738  357800  14312.0  1789.0
739  363000  14520.0  1815.0
740  367800  14712.0  1839.0
741  372400  14896.0  1862.0
742  376600  15064.0  1883.0

[740 rows x 3 columns]

### Cargamos los datos de la remuneración imponible promedio de los trabajadores estables (RIPTE):

In [37]:
df_RIPTE_parcial = hojas_eph["RIPTE"]
df_RIPTE_parcial.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Remuneración imponible promedio de los trabaja...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total país,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,En pesos,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Período,RIPTE,NaN,NaN,NaN,NaN,NaN,NaN
9,158.1_ICE_TIEMPO_0_0_13,158.1_REPTE_0_0_5,NaN,NaN,NaN,NaN,NaN,NaN
10,1994-07-01 00:00:00,874.87,NaN,NaN,NaN,NaN,NaN,NaN
11,1994-08-01 00:00:00,893,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_RIPTE_parcial.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Índice
386,2025-11-01 00:00:00,1611851.61,NaN,NaN,NaN,NaN,NaN,NaN
387,2025-12-01 00:00:00,1633547,NaN,NaN,NaN,NaN,NaN,NaN
388,2026-01-01 00:00:00,1646344.54,NaN,NaN,NaN,NaN,NaN,NaN
389,2026-02-01 00:00:00,1734357.18,NaN,NaN,NaN,NaN,NaN,NaN
390,2026-03-01 00:00:00,1775664.12,NaN,NaN,NaN,NaN,NaN,NaN
391,2026-04-01 00:00:00,1837609.35,NaN,NaN,NaN,NaN,NaN,NaN
392,2026-05-01 00:00:00,1849727.96,NaN,NaN,NaN,NaN,NaN,NaN
393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,Fuente: Ministerio de Capital Humano.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_RIPTE = format_df("RIPTE", hojas_eph, 10, -3, 8)
df_RIPTE

8                Período       RIPTE
0    1994-07-01 00:00:00      874.87
1    1994-08-01 00:00:00         893
2    1994-09-01 00:00:00      907.99
3    1994-10-01 00:00:00      910.75
4    1994-11-01 00:00:00      916.93
..                   ...         ...
378  2026-01-01 00:00:00  1646344.54
379  2026-02-01 00:00:00  1734357.18
380  2026-03-01 00:00:00  1775664.12
381  2026-04-01 00:00:00  1837609.35
382  2026-05-01 00:00:00  1849727.96

[383 rows x 2 columns]

## <center> Carguemos ahora ENGHo

### Cargamos Hogares:

In [40]:
df_ENGHO_hogares = pd.read_csv(ENGHO_DIR/"engho2018_hogares.txt", sep='|')
df_ENGHO_hogares.head()

,id,provincia,region,subregion,trimestre,anio,pondera,cv1c04,cv1c05_a,cv1c05_b,...,qinth_t,dinth_p,dinth_r,dinth_t,qinpch_p,qinpch_r,qinpch_t,dinpch_p,dinpch_r,dinpch_t
0,478229345,2,1,1A,4,2018,276,4,2.0,3.0,...,4,5,7,7,3,4,4,6,8,8
1,824935596,2,1,1A,4,2018,271,4,3.0,3.0,...,4,7,8,8,4,5,5,7,9,9
2,549385244,2,1,1A,1,2017,264,4,2.0,3.0,...,2,2,3,3,3,4,4,5,7,8
3,64338930,2,1,1A,3,2018,245,4,3.0,3.0,...,5,9,9,10,5,5,5,10,10,10
4,635779227,2,1,1A,3,2018,283,4,3.0,3.0,...,4,5,6,7,3,4,4,5,8,8

In [41]:
df_ENGHO_hogares.tail()

,id,provincia,region,subregion,trimestre,anio,pondera,cv1c04,cv1c05_a,cv1c05_b,...,qinth_t,dinth_p,dinth_r,dinth_t,qinpch_p,qinpch_r,qinpch_t,dinpch_p,dinpch_r,dinpch_t
21542,57618153,94,6,6B,3,2018,124,1,3.0,2.0,...,3,2,4,5,4,5,5,7,9,9
21543,551737923,94,6,6B,3,2018,123,1,3.0,2.0,...,4,4,7,8,5,5,5,10,10,10
21544,188896348,94,6,6B,1,2018,11,1,2.0,2.0,...,1,1,2,2,1,1,1,1,2,2
21545,127611813,94,6,6B,2,2018,68,1,3.0,3.0,...,5,9,10,10,4,5,5,8,9,10
21546,37138480,94,6,6B,2,2018,59,1,3.0,3.0,...,5,7,9,9,3,4,5,6,8,9

### Cargamos Personas:

In [42]:
df_ENGHO_personas = pd.read_csv(ENGHO_DIR/"engho2018_personas.txt", sep='|', low_memory = False)
df_ENGHO_personas.head()

,id,provincia,miembro,pondera,region,subregion,anio,trimestre,cp03,cp04,...,ibecaspub_imp,iotrosps,m_iotrosps,iotrosps_imp,itransfermon,m_itransfermon,itransfermon_imp,iautoconsumo,m_iautoconsumo,iautoconsumo_imp
0,478229345,2,1,276,1,1A,2018,4,83,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
1,478229345,2,2,276,1,1A,2018,4,82,2,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
2,824935596,2,1,271,1,1A,2018,4,75,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
3,824935596,2,2,271,1,1A,2018,4,51,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549385244,2,1,264,1,1A,2017,1,19,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0

### Cargamos gastos:

In [43]:
df_ENGHO_gastos = pd.read_csv(ENGHO_DIR/"engho2018_gastos.txt", sep='|', low_memory = False)
df_ENGHO_gastos.head()

,id,provincia,miembro,pondera,region,subregion,articulo,subclase,clase,grupo,division,r_imputado,cantidad,unmed,monto,forma_pago,tipo_negocio,modo_adq,lugar_adq
0,8558,14,0,749,2,2A,A0111105,A01111,A0111,A011,A01,2,1.732,K,186.19,1.0,3.0,1.0,2.0
1,8558,14,0,749,2,2A,A0111111,A01111,A0111,A011,A01,2,4.330,K,173.20,1.0,2.0,1.0,2.0
2,8558,14,0,749,2,2A,A0111111,A01111,A0111,A011,A01,2,10.825,K,433.00,1.0,3.0,1.0,2.0
3,8558,14,0,749,2,2A,A0111114,A01111,A0111,A011,A01,2,2.165,K,151.55,1.0,3.0,1.0,2.0
4,8558,14,0,749,2,2A,A0111201,A01112,A0111,A011,A01,2,2.165,K,73.61,1.0,3.0,1.0,2.0

In [44]:
df_ENGHO_gastos.tail()

,id,provincia,miembro,pondera,region,subregion,articulo,subclase,clase,grupo,division,r_imputado,cantidad,unmed,monto,forma_pago,tipo_negocio,modo_adq,lugar_adq
901799,999873115,82,0,388,2,2B,A0942101,A09421,A0942,A094,A09,2,1.0000,U,500.00,1.0,NaN,NaN,2.0
901800,999873115,82,0,388,2,2B,A1213211,A12132,A1213,A121,A12,2,465.4750,G,38.97,1.0,2.0,1.0,2.0
901801,999873115,82,0,388,2,2B,A1254101,A12541,A1254,A125,A12,2,0.3102,U,310.20,1.0,3.0,NaN,NaN
901802,999873115,82,2,388,2,2B,A0722102,A07221,A0722,A072,A07,2,23.8150,L,866.00,1.0,3.0,NaN,2.0
901803,999873115,82,3,388,2,2B,A1111217,A11112,A1111,A111,A11,1,12.9900,U,1558.80,1.0,9.0,NaN,2.0

## Dejamos listados todos los datasets descargados:

In [45]:
datasets = {
    "EPH SMVM": df_SMVM,
    "EPH RIPTE": df_RIPTE,
    "AUH Valor general": df_AUH_valor_general,
    "AUH Edad Titular": df_AUH_edad_titular,
    "IPC General": df_IPC_general_mensual,
    "IPC Canastas GBA": df_ipc_canasta_GBA,
    "IPC Canastas NEA": df_ipc_canasta_NEA,
    "IPC Canastas NOA": df_ipc_canasta_NOA,
    "IPC Canastas CUYO": df_ipc_canasta_CUYO,
    "IPC Canastas PAMPEANA": df_ipc_canasta_PAMPEANA,
    "IPC Canastas PATAGONIA": df_ipc_canasta_PATAGONIA,  
    "CBA": CBA,
    "CBT": CBT,
    "Pobreza_Indigencia": pobreza_indigencia,
    "ENGHo Hogares": df_ENGHO_hogares,
    "ENGHo Personas": df_ENGHO_personas,
    "ENGHo Gastos": df_ENGHO_gastos,
}

# <center> 3.  Revision, variables y tipos

In [46]:
for dataset, df in datasets.items():
    print(f"{dataset}: {df.shape}")

EPH SMVM: (740, 3)
EPH RIPTE: (383, 2)
AUH Valor general: (59, 5)
AUH Edad Titular: (34, 16)
IPC General: (115, 7)
IPC Canastas GBA: (109, 15)
IPC Canastas NEA: (109, 15)
IPC Canastas NOA: (109, 15)
IPC Canastas CUYO: (109, 15)
IPC Canastas PAMPEANA: (109, 15)
IPC Canastas PATAGONIA: (109, 15)
CBA: (117, 7)
CBT: (117, 7)
ENGHo Hogares: (21547, 134)
ENGHo Personas: (68725, 158)
ENGHo Gastos: (901804, 19)

In [47]:
df_ENGHO_personas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68725 entries, 0 to 68724
Columns: 158 entries, id to iautoconsumo_imp
dtypes: float64(97), int64(57), object(4)
memory usage: 82.8+ MB

### Veamos los tipos de cada dataset:

In [48]:
for dataset, df in datasets.items():
    print(f"Informacion de {dataset}: {df.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 3 to 742
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Mensual  740 non-null    object
 1   Diario   740 non-null    object
 2   Horario  740 non-null    object
dtypes: object(3)
memory usage: 17.5+ KB
Informacion de EPH SMVM: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Período  383 non-null    object
 1   RIPTE    383 non-null    object
dtypes: object(2)
memory usage: 6.1+ KB
Informacion de EPH RIPTE: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Periodo                            59 non-null     object
 1   Hijo                               59 non-null     object
 2   Hijo con Discapacidad              59 non-null     object
 3   Asignación por Embarazo            57 non-null     object
 4   Apoyo Alimentario - Ley 1000 días  31 non-null     object
dtypes: object(5)
memory usage: 2.4+ KB
Informacion de AUH Valor general: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Periodo        34 non-null     object
 1   15 - 19        34 non-null     object
 2   20 - 24        34 non-null     object
 3   25 - 29        34 non-null     object
 4   30 - 34        34 non-null     object
 5   35 - 39        34 non-null     object
 6   40 - 44        34 non-null     object
 7   45 - 49        34 non-null     object
 8   50 - 54        34 non-null     object
 9   55 - 59        34 non-null     object
 10  60 - 64        34 non-null     object
 11  65 - 69        34 non-null     object
 12  Más de 70      34 non-null     object
 13  Sin datos      34 non-null     object
 14  Total          34 non-null     object
 15  Edad Promedio  34 non-null     object
dtypes: object(16)
memory usage: 4.4+ KB
Informacion de AUH Edad Titular: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Período   115 non-null    object
 1   NACIONAL  115 non-null    object
 2   GBA       115 non-null    object
 3   PAMPEANA  115 non-null    object
 4   NEA       115 non-null    object
 5   NOA       115 non-null    object
 6   CUYO      115 non-null    object
dtypes: object(7)
memory usage: 6.4+ KB
Informacion de IPC General: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   Período                                                                       109 non-null    object
 1   Pan francés                          (kg)                                     109 non-null    object
 2   Harina de trigo común 000                                    (kg)             109 non-null    object
 3   Arroz blanco simple (kg)                                                      109 non-null    object
 4   Fideos secos tipo guisero                                           (500 gr)  109 non-null    object
 5   Carne picada común (kg)                                                       109 non-null    object
 6   Pollo entero                                       (kg)                       109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                        109 non-null    object
 8   Leche fresca entera sachet                                   (litro)          109 non-null    object
 9   Huevos de gallina (docena)                                                    109 non-null    object
 10  Papa                                                      (kg)                109 non-null    object
 11  Azúcar                                                  (kg)                  109 non-null    object
 12  Detergente líquido (750cc)                                                    109 non-null    object
 13  Lavandina                                  (1000 cc)                          109 non-null    object
 14  Jabón de tocador                 (125 gr)                                     109 non-null    object
dtypes: object(15)
memory usage: 12.9+ KB
Informacion de IPC Canastas GBA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   Periodo                                                                          109 non-null    datetime64[ns]
 1   Pan francés                                      (kg)                            109 non-null    object
 2   Harina de trigo común 000                                         (kg)           109 non-null    object
 3   Arroz blanco simple (kg)                                                         109 non-null    object
 4   Fideos secos tipo guisero                                              (500 gr)  109 non-null    object
 5   Carne picada común (kg)                                                          109 non-null    object
 6   Pollo entero                                    (kg)                             109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                           109 non-null    object
 8   Leche fresca entera sachet                          (litro)                      109 non-null    object
 9   Huevos de gallina (docena)                                                       109 non-null    object
 10  Papa                                  (kg)                                       109 non-null    object
 11  Azúcar                                                         (kg)              109 non-null    object
 12  Detergente líquido (750cc)                                                       109 non-null    object
 13  Lavandina                                       (1000 cc)                        109 non-null    object
 14  Jabón de tocador                  (125 gr)                                       109 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 12.9+ KB
Informacion de IPC Canastas NEA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   Periodo                                                                           109 non-null    datetime64[ns]
 1   Pan francés                           (kg)                                        109 non-null    object
 2   Harina de trigo común 000                                                   (kg)  109 non-null    object
 3   Arroz blanco simple (kg)                                                          109 non-null    object
 4   Fideos secos tipo guisero                                  (500 gr)               109 non-null    object
 5   Carne picada común (kg)                                                           109 non-null    object
 6   Pollo entero                             (kg)                                     109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                            109 non-null    object
 8   Leche fresca entera sachet                (litro)                                 109 non-null    object
 9   Huevos de gallina (docena)                                                        109 non-null    object
 10  Papa                                             (kg)                             109 non-null    object
 11  Azúcar                                                   (kg)                     109 non-null    object
 12  Detergente líquido (750cc)                                                        109 non-null    object
 13  Lavandina                                      (1000 cc)                          109 non-null    object
 14  Jabón de tocador                    (125 gr)                                      109 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 12.9+ KB
Informacion de IPC Canastas NOA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Periodo                                                                     109 non-null    datetime64[ns]
 1   Pan francés                               (kg)                              109 non-null    object
 2   Harina de trigo común 000                                       (kg)        109 non-null    object
 3   Arroz blanco simple (kg)                                                    109 non-null    object
 4   Fideos secos tipo guisero                                         (500 gr)  109 non-null    object
 5   Carne picada común (kg)                                                     109 non-null    object
 6   Pollo entero                   (kg)                                         109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                      109 non-null    object
 8   Leche fresca entera sachet                 (litro)                          109 non-null    object
 9   Huevos de gallina (docena)                                                  109 non-null    object
 10  Papa                                                           (kg)         109 non-null    object
 11  Azúcar                                            (kg)                      109 non-null    object
 12  Detergente líquido (750cc)                                                  109 non-null    object
 13  Lavandina                                  (1000 cc)                        109 non-null    object
 14  Jabón de tocador                  (125 gr)                                  109 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 12.9+ KB
Informacion de IPC Canastas CUYO: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Periodo                                                                109 non-null    datetime64[ns]
 1   Pan francés                                   (kg)                     109 non-null    object
 2   Harina de trigo común 000                              (kg)            109 non-null    object
 3   Arroz blanco simple (kg)                                               109 non-null    object
 4   Fideos secos tipo guisero                                    (500 gr)  109 non-null    object
 5   Carne picada común (kg)                                                109 non-null    object
 6   Pollo entero                   (kg)                                    109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                 109 non-null    object
 8   Leche fresca entera sachet                                 (litro)     109 non-null    object
 9   Huevos de gallina (docena)                                             109 non-null    object
 10  Papa                                                (kg)               109 non-null    object
 11  Azúcar                                           (kg)                  109 non-null    object
 12  Detergente líquido (750cc)                                             109 non-null    object
 13  Lavandina                  (1000 cc)                                   109 non-null    object
 14  Jabón de tocador                   (125 gr)                            109 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 12.9+ KB
Informacion de IPC Canastas PAMPEANA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 15 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   Periodo                                                                 109 non-null    datetime64[ns]
 1   Pan francés                                  (kg)                       109 non-null    object
 2   Harina de trigo común 000                                         (kg)  109 non-null    object
 3   Arroz blanco simple (kg)                                                109 non-null    object
 4   Fideos secos tipo guisero                                     (500 gr)  109 non-null    object
 5   Carne picada común (kg)                                                 108 non-null    object
 6   Pollo entero                            (kg)                            109 non-null    object
 7   Aceite de girasol         (1,5 litros)                                  109 non-null    object
 8   Leche fresca entera sachet                              (litro)         108 non-null    object
 9   Huevos de gallina (docena)                                              108 non-null    object
 10  Papa                                           (kg)                     109 non-null    object
 11  Azúcar                                    (kg)                          109 non-null    object
 12  Detergente líquido (750cc)                                              108 non-null    object
 13  Lavandina                         (1000 cc)                             108 non-null    object
 14  Jabón de tocador                (125 gr)                                108 non-null    object
dtypes: datetime64[ns](1), object(14)
memory usage: 12.9+ KB
Informacion de IPC Canastas PATAGONIA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   indice_tiempo      117 non-null    object
 1   gran_buenos_aires  117 non-null    float64
 2   cuyo               117 non-null    float64
 3   noreste            117 non-null    float64
 4   noroeste           117 non-null    float64
 5   pampeana           117 non-null    float64
 6   patagonia          117 non-null    float64
dtypes: float64(6), object(1)
memory usage: 6.5+ KB
Informacion de CBA: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   indice_tiempo      117 non-null    object
 1   gran_buenos_aires  117 non-null    float64
 2   cuyo               117 non-null    float64
 3   noreste            117 non-null    float64
 4   noroeste           117 non-null    float64
 5   pampeana           117 non-null    float64
 6   patagonia          117 non-null    float64
dtypes: float64(6), object(1)
memory usage: 6.5+ KB
Informacion de CBT: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21547 entries, 0 to 21546
Columns: 134 entries, id to dinpch_t
dtypes: float64(64), int64(69), object(1)
memory usage: 22.0+ MB
Informacion de ENGHo Hogares: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68725 entries, 0 to 68724
Columns: 158 entries, id to iautoconsumo_imp
dtypes: float64(97), int64(57), object(4)
memory usage: 82.8+ MB
Informacion de ENGHo Personas: None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901804 entries, 0 to 901803
Data columns (total 19 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            901804 non-null  int64
 1   provincia     901804 non-null  int64
 2   miembro       901804 non-null  int64
 3   pondera       901804 non-null  int64
 4   region        901804 non-null  int64
 5   subregion     901804 non-null  object
 6   articulo      901804 non-null  object
 7   subclase      901804 non-null  object
 8   clase         901804 non-null  object
 9   grupo         901804 non-null  object
 10  division      901804 non-null  object
 11  r_imputado    901804 non-null  int64
 12  cantidad      901804 non-null  float64
 13  unmed         901804 non-null  object
 14  monto         901804 non-null  float64
 15  forma_pago    892337 non-null  float64
 16  tipo_negocio  742234 non-null  float64
 17  modo_adq      601946 non-null  float64
 18  lugar_adq     876760 non-null  float64
dtypes: float64(6), int64(6), object(7)
memory usage: 130.7+ MB
Informacion de ENGHo Gastos: None

### Vemos que muchos datasets tiene los tipos mal colocados

In [49]:
for dataset, df in datasets.items():
    print(f"\n===== {dataset} =====")
    display(df.head())

===== EPH SMVM =====

8 Mensual Diario Horario
3    9800    392      49
4    9800    392      49
5    9800    392      49
6    9800    392      49
7   11550    462   57.75

===== EPH RIPTE =====

8              Período   RIPTE
0  1994-07-01 00:00:00  874.87
1  1994-08-01 00:00:00     893
2  1994-09-01 00:00:00  907.99
3  1994-10-01 00:00:00  910.75
4  1994-11-01 00:00:00  916.93

===== AUH Valor general =====

1,Periodo,Hijo,Hijo con Discapacidad,Asignación por Embarazo,Apoyo Alimentario - Ley 1000 días
0,2009-10-01 00:00:00,180,720,NaN,NaN
1,2010-10-01 00:00:00,220,880,NaN,NaN
2,2011-05-01 00:00:00,220,880,220,NaN
3,2011-09-01 00:00:00,270,1080,270,NaN
4,2012-09-01 00:00:00,340,1200,340,NaN

===== AUH Edad Titular =====

2,Periodo,15 - 19,20 - 24,25 - 29,30 - 34,35 - 39,40 - 44,45 - 49,50 - 54,55 - 59,60 - 64,65 - 69,Más de 70,Sin datos,Total,Edad Promedio
0,2016-12-08 00:00:00,127013,419998,455548,412583,360616,228488,126579,58702,18556,2491,243,113,805,2211735,31.696853
1,2017-12-03 00:00:00,117450,414527,462802,411328,363787,235520,130133,58503,18751,2611,258,96,796,2216562,31.835462
2,2018-12-08 00:00:00,111069,414334,477442,423139,363638,244929,133145,59397,19202,2973,271,81,821,2250441,31.928085
3,2019-12-01 00:00:00,102969,418238,516495,462762,389213,279372,151922,67610,22659,3848,336,143,213,2415780,32.315143
4,2020-12-06 00:00:00,83292,406988,538166,486265,396556,294895,161036,71700,23825,4470,438,172,406,2468209,32.617404

===== IPC General =====

4,Período,NACIONAL,GBA,PAMPEANA,NEA,NOA,CUYO
0,2016-12-01 00:00:00,100,100,100,100,100,100
1,2017-01-01 00:00:00,101.5859,101.313,101.7874,101.6727,101.6014,101.7074
2,2017-02-01 00:00:00,103.6859,103.8085,103.5312,103.4617,103.7115,103.2652
3,2017-03-01 00:00:00,106.1476,106.2627,105.8173,105.988,107.055,105.9238
4,2017-04-01 00:00:00,108.9667,109.0613,108.6912,108.3473,109.9626,109.4506

===== IPC Canastas GBA =====

5,Período,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01 00:00:00,38.64,10.67,20.96,19.08,72.2,34.45,50.41,20.96,33.23,13.9,19.16,19.53,15.7,13.99
1,2017-07-01 00:00:00,39.12,10.61,21.08,19.53,72.71,35.51,51.35,21.53,33.54,14.48,19.37,19.84,15.62,14.12
2,2017-08-01 00:00:00,39.43,10.65,21.25,19.73,73.4,36.21,52.35,21.72,33.63,14.35,19.58,20.1,15.64,14.24
3,2017-09-01 00:00:00,39.71,10.66,21.49,19.86,73.28,38.57,54.09,21.81,33.7,14.37,19.78,20.08,15.96,14.51
4,2017-10-01 00:00:00,39.89,10.61,21.74,20.13,73.75,39.3,54.68,21.95,33.93,15.34,20.12,20.55,16.13,14.6

===== IPC Canastas NEA =====

5,Periodo,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01,28.67,11.35,19.82,14.4,68.67,37.3,51.08,22.53,29.33,13.21,17.9,19.93,16.07,14.23
1,2017-07-01,28.99,11.05,20.32,14.34,70.58,36.99,51.05,23.27,29.27,12.56,17.99,20.53,15.96,14.21
2,2017-08-01,29.07,10.94,20.37,14.57,72.24,37.29,53.34,23.25,29.27,13.23,18.01,20.67,15.81,14.49
3,2017-09-01,29.4,11.06,20.07,14.7,74.83,39.05,54.33,23.39,29.32,13.51,18.37,20.34,15.77,14.79
4,2017-10-01,29.38,11.1,20.32,15.19,76.78,39.39,55.78,23.82,29.07,13.6,18.72,19.88,16.09,14.88

===== IPC Canastas NOA =====

5,Periodo,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01,32.32,10.53,18.48,13.44,81.89,36,51.46,21.55,30.08,11.33,16.35,23.05,14.75,14.65
1,2017-07-01,33.1,10.55,18.63,13.62,82.23,36.91,52.13,22.53,30.32,10.82,16.53,23.57,14.95,14.73
2,2017-08-01,33.25,10.59,19.16,13.78,82.43,37.48,52.96,22.58,30.47,11.21,16.54,23.92,15.18,15.05
3,2017-09-01,33.24,10.7,19.41,13.89,84.05,39.69,53.8,22.89,30.54,11.47,16.64,23.91,15.43,15.24
4,2017-10-01,33.57,10.85,19.74,13.93,84.82,40.48,54.7,22.76,30.81,11.55,16.87,24.34,15.74,15.31

===== IPC Canastas CUYO =====

5,Periodo,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01,28.12,10.45,18.28,17.36,72.9,34.22,48.26,23.22,35.84,13.01,17.86,21.91,14.23,14.21
1,2017-07-01,28.34,10.28,18.86,17.92,73.7,36.16,49.07,23.95,36.04,12.83,18.13,22.11,14.61,14.25
2,2017-08-01,28.82,10.46,19.27,18.54,73.72,36.91,49.39,24.04,35.29,12.98,18.29,22.15,14.59,14.78
3,2017-09-01,28.99,10.49,19.13,18.81,74.82,39.39,51.16,23.85,35.95,13.28,18.69,21.4,15.11,14.89
4,2017-10-01,29.35,10.58,19.6,18.85,73.88,40,51.56,24.06,35.41,14.12,19.01,22.21,15.41,14.99

===== IPC Canastas PAMPEANA =====

5,Periodo,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01,31.42,11.19,20.79,16.91,76.04,36.61,52.46,22.63,33,13.59,18.62,21.94,14.7,14.27
1,2017-07-01,31.93,11.17,21.22,17.22,77.33,37.44,53.57,23.42,33.05,13.93,18.94,22.2,14.59,14.45
2,2017-08-01,32.32,11.19,21.76,17.79,77,38.37,54.91,23.58,33.4,14.26,19.21,22.47,14.84,14.68
3,2017-09-01,32.62,11.25,21.97,18.01,77.31,40.54,55.8,23.53,33.11,14.53,19.45,22.38,15.06,14.82
4,2017-10-01,33.03,11.35,21.92,18.07,78.34,40.9,55.93,23.64,33.28,14.92,19.73,22.53,15.11,14.95

===== IPC Canastas PATAGONIA =====

5,Periodo,Pan francés (kg),Harina de trigo común 000 (kg),Arroz blanco simple (kg),Fideos secos tipo guisero (500 gr),Carne picada común (kg),Pollo entero (kg),"Aceite de girasol (1,5 litros)",Leche fresca entera sachet (litro),Huevos de gallina (docena),Papa (kg),Azúcar (kg),Detergente líquido (750cc),Lavandina (1000 cc),Jabón de tocador (125 gr)
0,2017-06-01,38.43,12.14,25.82,20.68,91.12,42.98,50.31,23.82,43.34,19.44,21.34,34.48,16.2,15.09
1,2017-07-01,38.68,11.79,26.33,21.02,91.64,43.04,50.25,24.36,43.78,18.95,21.38,34.91,16.21,15.3
2,2017-08-01,38.84,11.75,26.49,21.32,92.76,43.33,51.17,24.53,44.34,19.55,21.52,35.98,16.57,15.6
3,2017-09-01,39.49,12.06,26.52,20.98,94.13,44.73,51.64,25.08,43.75,19.71,21.72,34.89,17.14,15.58
4,2017-10-01,39.88,12.24,27.16,21.32,96.01,44.73,53.71,25.03,43.7,20.55,22.24,35.51,17.65,15.68

===== CBA =====

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
0,2016-04-01,1514.53,1358.29,1371.62,1333.91,1514.96,1556.96
1,2016-05-01,1561.35,1398.20,1404.27,1369.37,1562.75,1604.30
2,2016-06-01,1614.32,1445.22,1447.63,1413.77,1614.33,1661.42
3,2016-07-01,1666.48,1494.04,1496.21,1458.24,1660.19,1713.67
4,2016-08-01,1675.05,1496.09,1501.91,1459.38,1662.99,1723.86

===== CBT =====

,indice_tiempo,gran_buenos_aires,cuyo,noreste,noroeste,pampeana,patagonia
0,2016-04-01,3665.17,3504.40,3099.86,2987.95,3666.21,4281.63
1,2016-05-01,3825.30,3649.31,3229.82,3122.17,3828.74,4459.96
2,2016-06-01,3938.94,3757.58,3315.07,3209.27,3938.96,4602.13
3,2016-07-01,4032.88,3854.62,3396.40,3281.04,4017.66,4712.59
4,2016-08-01,4036.87,3844.95,3394.32,3269.01,4007.81,4723.38

===== ENGHo Hogares =====

,id,provincia,region,subregion,trimestre,anio,pondera,cv1c04,cv1c05_a,cv1c05_b,...,qinth_t,dinth_p,dinth_r,dinth_t,qinpch_p,qinpch_r,qinpch_t,dinpch_p,dinpch_r,dinpch_t
0,478229345,2,1,1A,4,2018,276,4,2.0,3.0,...,4,5,7,7,3,4,4,6,8,8
1,824935596,2,1,1A,4,2018,271,4,3.0,3.0,...,4,7,8,8,4,5,5,7,9,9
2,549385244,2,1,1A,1,2017,264,4,2.0,3.0,...,2,2,3,3,3,4,4,5,7,8
3,64338930,2,1,1A,3,2018,245,4,3.0,3.0,...,5,9,9,10,5,5,5,10,10,10
4,635779227,2,1,1A,3,2018,283,4,3.0,3.0,...,4,5,6,7,3,4,4,5,8,8

===== ENGHo Personas =====

,id,provincia,miembro,pondera,region,subregion,anio,trimestre,cp03,cp04,...,ibecaspub_imp,iotrosps,m_iotrosps,iotrosps_imp,itransfermon,m_itransfermon,itransfermon_imp,iautoconsumo,m_iautoconsumo,iautoconsumo_imp
0,478229345,2,1,276,1,1A,2018,4,83,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
1,478229345,2,2,276,1,1A,2018,4,82,2,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
2,824935596,2,1,271,1,1A,2018,4,75,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0
3,824935596,2,2,271,1,1A,2018,4,51,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549385244,2,1,264,1,1A,2017,1,19,1,...,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0

===== ENGHo Gastos =====

,id,provincia,miembro,pondera,region,subregion,articulo,subclase,clase,grupo,division,r_imputado,cantidad,unmed,monto,forma_pago,tipo_negocio,modo_adq,lugar_adq
0,8558,14,0,749,2,2A,A0111105,A01111,A0111,A011,A01,2,1.732,K,186.19,1.0,3.0,1.0,2.0
1,8558,14,0,749,2,2A,A0111111,A01111,A0111,A011,A01,2,4.330,K,173.20,1.0,2.0,1.0,2.0
2,8558,14,0,749,2,2A,A0111111,A01111,A0111,A011,A01,2,10.825,K,433.00,1.0,3.0,1.0,2.0
3,8558,14,0,749,2,2A,A0111114,A01111,A0111,A011,A01,2,2.165,K,151.55,1.0,3.0,1.0,2.0
4,8558,14,0,749,2,2A,A0111201,A01112,A0111,A011,A01,2,2.165,K,73.61,1.0,3.0,1.0,2.0

### Veamos los valores faltantes:

In [50]:
for dataset, df in datasets.items():
    print(f"\n===== Valores faltantes en {dataset} =====")
    display(df.isna().sum().sum())

===== Valores faltantes en EPH SMVM =====

0

===== Valores faltantes en EPH RIPTE =====

0

===== Valores faltantes en AUH Valor general =====

30

===== Valores faltantes en AUH Edad Titular =====

0

===== Valores faltantes en IPC General =====

0

===== Valores faltantes en IPC Canastas GBA =====

0

===== Valores faltantes en IPC Canastas NEA =====

0

===== Valores faltantes en IPC Canastas NOA =====

0

===== Valores faltantes en IPC Canastas CUYO =====

0

===== Valores faltantes en IPC Canastas PAMPEANA =====

0

===== Valores faltantes en IPC Canastas PATAGONIA =====

6

===== Valores faltantes en CBA =====

0

===== Valores faltantes en CBT =====

0

===== Valores faltantes en ENGHo Hogares =====

34989

===== Valores faltantes en ENGHo Personas =====

3339075

===== Valores faltantes en ENGHo Gastos =====

493939

#### En general solo en los datasets de ENGHo, tenemos gran cantidad de valores faltantes.

### Veamos los valores duplicados:

In [51]:
for dataset, df in datasets.items():
    print(f"\n===== Valores duplicados en {dataset} =====")
    display(df.duplicated().sum())

===== Valores duplicados en EPH SMVM =====

538

===== Valores duplicados en EPH RIPTE =====

0

===== Valores duplicados en AUH Valor general =====

0

===== Valores duplicados en AUH Edad Titular =====

0

===== Valores duplicados en IPC General =====

0

===== Valores duplicados en IPC Canastas GBA =====

0

===== Valores duplicados en IPC Canastas NEA =====

0

===== Valores duplicados en IPC Canastas NOA =====

0

===== Valores duplicados en IPC Canastas CUYO =====

0

===== Valores duplicados en IPC Canastas PAMPEANA =====

0

===== Valores duplicados en IPC Canastas PATAGONIA =====

0

===== Valores duplicados en CBA =====

0

===== Valores duplicados en CBT =====

0

===== Valores duplicados en ENGHo Hogares =====

0

===== Valores duplicados en ENGHo Personas =====

0

===== Valores duplicados en ENGHo Gastos =====

0

#### No encontramos valores duplicados en los datasets

# <center>4 . Exportamos las bases en un formato csv

In [65]:
for dataset, df in datasets.items():
    print(f"\n===== Guardando {dataset} en un csv =====")
    os.makedirs(INTERIM_DIR, exist_ok=True)
    name = dataset.replace(" ", "_").lower()
    save_csv(df, name, INTERIM_DIR)

===== Guardando EPH SMVM en un csv =====
eph_smvm

===== Guardando EPH RIPTE en un csv =====
eph_ripte

===== Guardando AUH Valor general en un csv =====
auh_valor_general

===== Guardando AUH Edad Titular en un csv =====
auh_edad_titular

===== Guardando IPC General en un csv =====
ipc_general

===== Guardando IPC Canastas GBA en un csv =====
ipc_canastas_gba

===== Guardando IPC Canastas NEA en un csv =====
ipc_canastas_nea

===== Guardando IPC Canastas NOA en un csv =====
ipc_canastas_noa

===== Guardando IPC Canastas CUYO en un csv =====
ipc_canastas_cuyo

===== Guardando IPC Canastas PAMPEANA en un csv =====
ipc_canastas_pampeana

===== Guardando IPC Canastas PATAGONIA en un csv =====
ipc_canastas_patagonia

===== Guardando CBA en un csv =====
cba

===== Guardando CBT en un csv =====
cbt

===== Guardando ENGHo Hogares en un csv =====
engho_hogares

===== Guardando ENGHo Personas en un csv =====
engho_personas

===== Guardando ENGHo Gastos en un csv =====
engho_gastos